Repository team113/messenger, pull requests merged in 2022-08, with the labels that each got.

#47 Mobile call secondary view resize (#46)
  CHANGELOG.md
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/minimizable_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX

#53 Fix mobile bottom dock on minimizing (#50)
  CHANGELOG.md
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/minimizable_view.dart
Labels: enhancement, k::UI/UX

#56 Add joining call buttons with and w/o video (#51)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
Labels: enhancement, k::UI/UX

#37 Fix secondary view overlaying by buttons dock in `Call` (#36)
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/scaler.dart
  lib/ui/page/home/widget/animated_slider.dart
  lib/util/platform_utils.dart
Labels: enhancement, k::UI/UX, k::refactor

#60 Fix popup call on focus change
  CHANGELOG.md
  lib/ui/page/call/controller.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::UI/UX

#48 Add E2E CI stage
  .editorconfig
  .env
  .github/workflows/ci.yml
  .gitignore
  Makefile
  dev/backend.toml
  dev/coturn/redis.conf
  dev/coturn/turnserver.conf
  dev/mailhog/auth.passwd
  dev/mailhog/mailhog.conf
  dev/medea.toml
  dev/nginx.conf
  docker-compose.yml
  test/e2e/features/auth/create_account/.feature
Labels: enhancement, k::deploy, k::testing, k::toolchain

#62 Try to re-create `RoomHandle` on new `ChatCallRoomJoinLink`s
  lib/domain/model/ongoing_call.dart
Labels: enhancement, k::design

#22 Handle media acquisition exception
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/page/settings/media/view.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::refactor

#77 Add macOS `.app` building
  .github/workflows/ci.yml
  Makefile
  macos/Podfile.lock
Labels: enhancement, k::toolchain, platform::macos

#79 Fix video enabling in solo call (#75)
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
Labels: enhancement, k::UI/UX

#73 Implement `Helm` build and release
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  docker-compose.yml
  helm/.editorconfig
  helm/messenger/.helmignore
  helm/messenger/CHANGELOG.md
  helm/messenger/Chart.yaml
  helm/messenger/LICENSE
  helm/messenger/README.md
  helm/messenger/conf/nginx.conf
  helm/messenger/templates/NOTES.txt
  helm/messenger/templates/_helpers.tpl
  helm/messenger/templates/configmap.yaml
  helm/messenger/templates/deployment.yaml
  helm/messenger/templates/ingress.yaml
  helm/messenger/templates/secret.htpasswd.yaml
  helm/messenger/templates/secret.registry.yaml
  helm/messenger/templates/secret.sftp.yaml
  helm/messenger/templates/service.sftp.yaml
  helm/messenger/templates/service.yaml
  helm/messenger/values.yaml
Labels: feature, k::deploy, k::toolchain

#80 Add mobile call minimizing on back button (#76)
  CHANGELOG.md
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, platform::android

#83 Fix `Incorrect input` after changing password on `MyProfile` page (#81)
  CHANGELOG.md
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::UI/UX

#86 Make `GraphQlProvider` exceptions const
  lib/domain/service/call.dart
  lib/domain/service/chat.dart
  lib/provider/gql/base.dart
  lib/provider/gql/components/chat.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/store/chat_rx.dart
  test/unit/auth_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/contact_rename_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_gallery_test.dart
  test/unit/my_profile_phones_test.dart
  test/widget/password_recovery_test.dart
Labels: enhancement, k::refactor

#90 Fix call ringtone not being looped on macOS
  CHANGELOG.md
  lib/ui/worker/call.dart
Labels: enhancement, k::refactor

#84 Fix macOS linking issues
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Info.plist
  macos/Runner/Release.entitlements
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor, platform::macos

#106 Display `MyUser.unreadChatsCount` on macOS application icon
  .github/workflows/ci.yml
  CHANGELOG.md
  lib/ui/worker/my_user.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feature, k::UI/UX, platform::macos

#112 Prevent device from sleeping while in Call (#92)
  CHANGELOG.md
  lib/ui/page/popup_call/controller.dart
  lib/ui/worker/call.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor
