Repository team113/messenger, pull requests merged in 2022-06, with the labels that each got.

#1 Bootstrap CI
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature proposal.md
  .github/ISSUE_TEMPLATE/Question.md
  .github/ISSUE_TEMPLATE/Roadmap.md
  .github/ISSUE_TEMPLATE/Task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/Bugfix.md
  .github/PULL_REQUEST_TEMPLATE/Release.md
  .github/PULL_REQUEST_TEMPLATE/Roadmap.md
  .github/dependabot.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  README.md
Labels: k::documentation, enhancement, feature, k::toolchain

#14 Fix android native notification on incoming call (#13)
  CHANGELOG.md
  lib/ui/worker/background/src/main.dart
Labels: enhancement, k::UI/UX, platform::android

#15 Group creation overlay has no avatars (#2)
  CHANGELOG.md
  lib/domain/repository/contact.dart
  lib/domain/service/contact.dart
  lib/store/contact.dart
  lib/store/contact_rx.dart
  lib/ui/page/call/add_dialog_member/controller.dart
  lib/ui/page/call/add_dialog_member/view.dart
  lib/ui/page/home/page/chat/info/add_member/controller.dart
  lib/ui/page/home/page/chat/info/add_member/view.dart
  lib/ui/page/home/page/chat/widget/add_contact_list_tile.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/tab/chats/create_group/controller.dart
  lib/ui/page/home/tab/chats/create_group/view.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
Labels: enhancement, k::UI/UX, k::refactor
