Repository team113/messenger, pull requests merged in 2022-09, with the labels that each got.

#94 Fix `FLUTTER_VER` env `Makefile` variable
  Makefile
Labels: enhancement, k::toolchain

#59 Implement optimistic mutations in `Chat`s store (#43)
  lib/domain/model/user.dart
  lib/domain/repository/chat.dart
  lib/domain/service/chat.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_hide_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#117 Fix screen share prompt absence
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
Labels: enhancement, k::UI/UX

#114 Add local `User`s searching in `UserService.search` (#65)
  lib/domain/service/user.dart
  lib/store/user.dart
  lib/ui/page/home/widget/user_search_bar/controller.dart
  lib/ui/page/home/widget/user_search_bar/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#121 Refactor code to use `AuthService.userId` instead of `MyUserService`
  lib/domain/service/chat.dart
  lib/provider/hive/contact.dart
  lib/routes.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/contact_rename_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_delete_message_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_leave_test.dart
  test/widget/chat_members_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/contact_rename_test.dart
  test/widget/my_profile_gallery_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#115 Split large ChatMessages into multiple ChatMessages (#100)
  CHANGELOG.md
  lib/domain/model/chat_item.dart
  lib/domain/service/chat.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/split_messages/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/expect_n_widget.dart
  test/e2e/steps/text_field.dart
  test/unit/chat_split_message_test.dart
Labels: feature, k::UI/UX

#39 Add password reminder on logout
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/controller.dart
  test/e2e/features/home/logout/.feature
  test/e2e/parameters/keys.dart
Labels: enhancement, k::UI/UX

#139 Add multiline support to `ChatController.send` field
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/widget/dropdown.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::UI/UX

#49 Unify disabling incoming video behavior in `Call`s (#40)
  lib/domain/model/ongoing_call.dart
  lib/domain/service/call.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/page/settings/media/controller.dart
  lib/ui/page/home/page/settings/media/view.dart
  lib/util/obs/list.dart
  lib/util/obs/rxlist.dart
  lib/util/obs/rxmap.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#12 Implement attachments saving (#11)
  CHANGELOG.md
  android/app/src/main/AndroidManifest.xml
  assets/conf.toml
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/Runner/Info.plist
  lib/config.dart
  lib/domain/model/attachment.dart
  lib/domain/model/precise_date_time/src/web.dart
  lib/provider/gql/components/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/widget/gallery.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/util/platform_utils.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Release.entitlements
  pubspec.lock
  pubspec.yaml
  test/e2e/configuration.dart
  test/e2e/features/chat/attachments_saving/.feature
  test/e2e/mock/platform_utils.dart
  test/e2e/parameters/download_status.dart
  test/e2e/steps/download_file.dart
  test/e2e/steps/sends_attachment.dart
  test/e2e/steps/tap_widget.dart
  test/e2e/steps/wait_until_file_status.dart
Labels: enhancement, feature, k::UI/UX, k::config, k::refactor

#143 Fix attachments saving e2e tests
  test/e2e/parameters/download_status.dart
Labels: enhancement, k::testing

#129 Add `HomeView` background setting and displaying (#123)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model_type_id.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/background.dart
  lib/routes.dart
  lib/store/settings.dart
  lib/themes.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/personalization/controller.dart
  lib/ui/page/home/page/personalization/view.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  test/unit/call_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_delete_message_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_leave_test.dart
  test/widget/chat_members_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/contact_rename_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#150 Display `Call`'s title and duration in fullscreen popup (#74)
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX

#148 Add `User.online` indicators to `AvatarWidget` (#130)
  CHANGELOG.md
  lib/store/my_user.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/add_contact_list_tile.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/user_search_bar/view.dart
Labels: enhancement, k::UI/UX
