Repository team113/messenger, pull requests merged in 2022-12, with the labels that each got.

#224 Implement optimistic mutations in `MyUser`s store (#43)
  lib/store/my_user.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/retry_image.dart
Labels: enhancement, k::UI/UX, k::refactor

#227 Implement optimistic mutations in `Contact` store (#43)
  lib/store/contact.dart
Labels: enhancement, k::UI/UX, k::refactor

#206 Implement chat's search field (#205)
  CHANGELOG.md
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/chats/widget/search_user_tile.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/ui/page/home/widget/contact_tile.dart
  lib/ui/widget/context_menu/region.dart
  test/e2e/configuration.dart
  test/e2e/features/home/chats_searching/.feature
  test/e2e/parameters/keys.dart
  test/e2e/parameters/search_category.dart
  test/e2e/steps/contact.dart
  test/e2e/steps/see_search_results.dart
Labels: enhancement, k::UI/UX, k::refactor

#221 Make `DateTimeElement` headers to disappear when no scrolling in `Chat` (#215)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  pubspec.lock
Labels: enhancement, k::UI/UX

#185 Refactor `CallService` (#178)
  lib/domain/repository/call.dart
  lib/domain/service/call.dart
  lib/routes.dart
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/tab/chats/controller.dart
  test/mock/graphql_provider.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_leave_test.dart
  test/widget/chat_members_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/contact_rename_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#245 Redesign desktop context menu
  CHANGELOG.md
  assets/icons/audio_off_small.svg
  assets/icons/video_off_small.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/widget/context_menu/menu.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/context_menu/region.dart
Labels: enhancement, k::UI/UX, k::refactor

#246 Redesign `Chat` tile in mobile `Call` UI (#232)
  CHANGELOG.md
  build.yaml
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/tab/chats/widget/hovered_ink.dart
  lib/ui/page/home/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#249 Redesign `ModalPopup`s
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/api/backend/graphql/mutation/user/ResetUserPassword.graphql
  lib/provider/gql/components/auth.dart
  lib/provider/gql/exceptions.dart
  lib/themes.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/contact_tile.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/outlined_rounded_button.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/sending_status/attachments.feature
  test/e2e/features/chat/sending_status/messages.feature
  test/e2e/features/home/introduction/.feature
  test/e2e/features/home/logout/.feature
  test/e2e/features/my_user/online_status/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/tap_widget.dart
  test/e2e/steps/wait_to_settle.dart
  test/widget/password_recovery_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#237 Implement favorite chat contacts (#223)
  CHANGELOG.md
  lib/api/backend/graphql/mutation/contact/FavoriteChatContact.graphql
  lib/api/backend/graphql/mutation/contact/UnfavoriteChatContact.graphql
  lib/api/backend/graphql/parsers/contact.dart
  lib/domain/model/contact.dart
  lib/domain/repository/contact.dart
  lib/domain/service/contact.dart
  lib/provider/gql/components/contact.dart
  lib/provider/gql/exceptions.dart
  lib/store/contact.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/contact_tile.dart
  test/e2e/configuration.dart
  test/e2e/features/contact/favorite/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/contact.dart
  test/e2e/steps/contact_is_favorite.dart
  test/e2e/steps/long_press_contact.dart
  test/e2e/steps/see_contact_position.dart
  test/e2e/steps/see_favorite_contact.dart
  test/e2e/steps/tap_widget.dart
  test/e2e/world/custom_world.dart
  test/widget/contact_rename_test.dart
Labels: enhancement, feature, k::UI/UX, k::refactor

#251 Redesign `Chat.muted` visual indicator (#248)
  CHANGELOG.md
  assets/icons/muted.svg
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/mute_chat_popup/controller.dart
  lib/ui/page/home/tab/chats/mute_chat_popup/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  test/e2e/features/chat/mute/.feature
  test/e2e/parameters/keys.dart
Labels: enhancement, k::UI/UX, k::refactor

#254 Redesign `User` page (#252)
  CHANGELOG.md
  assets/icons/btn_mute.svg
  assets/icons/btn_unmute.svg
  assets/icons/chat.svg
  assets/icons/delete.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/widget/block.dart
  test/e2e/configuration.dart
  test/e2e/features/user/subscription/.feature
  test/e2e/steps/updates_name.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#235 Implement `ChatContact`s sorting on `Contact`s tab (#226)
  CHANGELOG.md
  assets/icons/sort_abc.svg
  assets/icons/sort_time.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/application_settings.dart
  lib/store/contact.dart
  lib/store/settings.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#228 Screen share device choosing (#222)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/media_settings.dart
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/screen_share/controller.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#266 Add Fluent messages for FCM notifications
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
Labels: enhancement, k::UI/UX

#260 Implement searching on `Contact`s tab (#259)
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/screen_share/controller.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/search_user_tile.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  test/e2e/features/home/contacts_searching/.feature
  test/e2e/steps/long_press_chat.dart
Labels: enhancement, feature, k::UI/UX

#244 Redesign `MyProfile` page (#243)
  CHANGELOG.md
  assets/icons/timer.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/routes.dart
  lib/store/my_user.dart
  lib/themes.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/dropdown.dart
  lib/ui/page/home/page/my_profile/widget/field_button.dart
  lib/ui/page/home/page/personalization/controller.dart
  lib/ui/page/home/page/personalization/view.dart
  lib/ui/page/home/page/settings/controller.dart
  lib/ui/page/home/page/settings/media/controller.dart
  lib/ui/page/home/page/settings/media/view.dart
  lib/ui/page/home/page/settings/view.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/login/view.dart
  lib/ui/widget/animations.dart
  lib/ui/widget/outlined_rounded_button.dart
  lib/ui/widget/selector.dart
  lib/ui/widget/text_field.dart
  lib/ui/widget/widget_button.dart
  pubspec.lock
  test/e2e/configuration.dart
  test/e2e/features/auth/create_account/.feature
  test/e2e/features/l10n/.feature
  test/e2e/steps/sees_as_online.dart
  test/widget/chat_direct_link_user_test.dart
  test/widget/my_profile_emails_test.dart
  test/widget/my_profile_gallery_test.dart
  test/widget/my_profile_phones_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#265 Redesign `ChatInfo` page (#256)
  CHANGELOG.md
  assets/icons/copy.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/store/chat.dart
  lib/store/my_user.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/page/chat/info/add_member/controller.dart
  lib/ui/page/home/page/chat/info/add_member/view.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/members/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/tap_search_result.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_members_test.dart
  test/widget/chat_rename_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#268 Add delay to `Draggable`s in `Dock` (#261)
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/widget/dock.dart
  test/e2e/features/chat/members/.feature
Labels: enhancement, k::UI/UX

#275 Redesign `MyUser.status` selector (#271)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/api/backend/graphql/mutation/user/UpdateUserStatus.graphql
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/provider/gql/components/user.dart
  lib/store/my_user.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/field_button.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/menu/status/controller.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/rmb_detector.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::UI/UX, k::refactor

#280 Adjust Fluent messages for FCM notifications
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
Labels: enhancement, k::UI/UX

#279 Transforming `Call`-dialog into `Call`-group being broken
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/event/chat.dart
Labels: enhancement, k::refactor

#277 Add blacklisted `User`s list (#267)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  build.yaml
  lib/api/backend/graphql/fragments/PageInfo.graphql
  lib/api/backend/graphql/parsers/user.dart
  lib/api/backend/graphql/query/user/GetBlacklist.graphql
  lib/domain/model_type_id.dart
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/provider/gql/components/user.dart
  lib/provider/hive/blacklist.dart
  lib/routes.dart
  lib/store/model/my_user.dart
  lib/store/my_user.dart
  lib/store/user_rx.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/blacklist/controller.dart
  lib/ui/page/home/page/my_profile/blacklist/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  test/unit/chat_direct_link_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_gallery_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/widget/auth_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX
