Repository team113/messenger, pull requests merged in 2022-11, with the labels that each got.

#193 Fix reversed order of message replies (#192)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
Labels: enhancement, k::UI/UX

#198 Fix RMB on `VideoThumbnail` opens default context menu on Web (#196)
  CHANGELOG.md
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/widget/menu_interceptor/src/non_web.dart
  test/unit/date_time_to_short_test.dart
Labels: enhancement, k::UI/UX

#197 `More` panel hides when hovering below `Dock` (#125)
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX, platform::windows, platform::web

#191 Scale down dragged `Participants` in `Call` (#190)
  CHANGELOG.md
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  test/e2e/steps/wait_until_widget.dart
Labels: enhancement, k::UI/UX

#188 Implement swipe to reply in `Chat` (#134)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/animated_offset.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/features/chat/delete_messages/.feature
  test/e2e/parameters/keys.dart
  test/unit/date_time_to_short_test.dart
  test/widget/chat_delete_message_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#177 Use persisted `ChatCallCredentials` in `Call`s
  lib/domain/model/chat_call.dart
  lib/domain/model/ongoing_call.dart
  lib/domain/model_type_id.dart
  lib/domain/repository/call.dart
  lib/domain/service/call.dart
  lib/provider/hive/chat_call_credentials.dart
  lib/routes.dart
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_leave_test.dart
  test/widget/chat_members_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/contact_rename_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#173 Persist a draft `ChatMessage` (#102)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/chat.dart
  lib/main.dart
  lib/provider/hive/base.dart
  lib/provider/hive/draft.dart
  lib/routes.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/ui/widget/text_field.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/draft/.feature
  test/e2e/steps/go_to.dart
  test/e2e/steps/see_draft.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_leave_test.dart
  test/widget/chat_members_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/contact_rename_test.dart
  test/widget/user_profile_test.dart
Labels: feature, k::UI/UX, k::design

#194 Synchronize `MyUser` with `User` it represents
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/routes.dart
  lib/store/my_user.dart
  lib/store/user.dart
  lib/ui/page/home/widget/chat_tile.dart
  test/unit/chat_direct_link_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_gallery_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/widget/chat_direct_link_user_test.dart
  test/widget/my_profile_emails_test.dart
  test/widget/my_profile_gallery_test.dart
  test/widget/my_profile_phones_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX

#204 Add quick status change menu (#203)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/participant/view.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/app_bar.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/widget/context_menu/menu.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/selector.dart
  lib/util/platform_utils.dart
Labels: enhancement, k::UI/UX, k::refactor

#213 Exiting from macOS fullscreen `Call` is choppy (#207)
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX, platform::macos

#210 Persist call hint indicators (#200)
  lib/domain/model/application_settings.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/application_settings.dart
  lib/store/settings.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX

#217 Display ImageAttachment miniatures instead of [N attachments] text (#214)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/chat_tile.dart
Labels: enhancement, k::UI/UX, k::refactor

#164 Backoff retry failed images (#126)
  CHANGELOG.md
  lib/config.dart
  lib/domain/model/precise_date_time/src/non_web.dart
  lib/domain/model/precise_date_time/src/web.dart
  lib/domain/model_type_id.dart
  lib/provider/gql/base.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/gallery.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/util/platform_utils.dart
  lib/util/web/web.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/configuration.dart
  test/e2e/features/chat/attachments_fetching/.feature
  test/e2e/hook/reset_app.dart
  test/e2e/parameters/fetch_status.dart
  test/e2e/steps/in_chat_with.dart
  test/e2e/steps/internet.dart
  test/e2e/steps/sends_attachment.dart
  test/e2e/steps/wait_until_attachment_fetched.dart
  test/widget/my_profile_gallery_test.dart
Labels: enhancement, k::UI/UX, k::refactor
