Repository team113/messenger, pull requests merged in 2022-10, with the labels that each got.

#154 Fix `WebUtils.cleanIndexedDb` not working on Web
  .gitignore
  CHANGELOG.md
  lib/util/web/web.dart
  web/index.html
Labels: enhancement, k::refactor

#147 Refactor and redesign `ContextMenu` (#132)
  CHANGELOG.md
  assets/icons/copy_small.svg
  assets/icons/delete_small.svg
  assets/icons/edit.svg
  assets/icons/forward.svg
  assets/icons/reply.svg
  assets/icons/send_small.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/config.dart
  lib/routes.dart
  lib/themes.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/my_profile/widget/copyable.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/sharable.dart
  lib/ui/widget/context_menu/menu.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/context_menu/overlay.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/modal_popup.dart
  lib/util/platform_utils.dart
  test/e2e/features/chat/sending_status/messages.feature
  test/e2e/parameters/keys.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_delete_message_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_leave_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/contact_rename_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#157 Bump up project version to 0.1.0-alpha.6.1
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#156 `ChatMessage` splitting E2E test is flaky (#149)
  test/e2e/configuration.dart
  test/e2e/features/chat/split_messages/.feature
  test/e2e/steps/expect_n_widget.dart
  test/e2e/steps/scroll_chat.dart
Labels: enhancement, k::testing

#138 Refactor `ChatView` to display `ListElement`s (#131)
  lib/domain/repository/chat.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/util/obs/rxlist.dart
  lib/util/obs/rxsplay.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#159 Persist `CallButton`s positions in `Call` (#137)
  CHANGELOG.md
  lib/domain/model/application_settings.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/application_settings.dart
  lib/store/settings.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/view.dart
  lib/ui/page/call/widget/dock.dart
Labels: enhancement, k::UI/UX

#161 Redesign style of `ChatMemberInfo` (#158)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/themes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
  lib/ui/page/home/tab/chats/view.dart
  test/unit/datetime_relative_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#169 Pressing Escape breaks fullscreen in Call (#166)
  CHANGELOG.md
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX, platform::macos

#171 Don't show notifications when application is focused (#128)
  CHANGELOG.md
  android/app/build.gradle
  lib/domain/service/notification.dart
  lib/util/platform_utils.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::UI/UX

#180 Fix flaky attachment downloading E2E test(#175)
  test/e2e/mock/platform_utils.dart
Labels: enhancement, k::testing

#162 Redesign `Attachment`s and style of `ChatMessage`s (#151)
  CHANGELOG.md
  assets/icons/download.svg
  assets/icons/download_cancel.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/service/chat.dart
  lib/store/chat_rx.dart
  lib/themes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  test/widget/chat_attachment_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#170 Redesign `ChatView` (#133)
  CHANGELOG.md
  assets/icons/arrow_left.svg
  assets/icons/attach.svg
  assets/icons/chat_audio_call.svg
  assets/icons/chat_video_call.svg
  assets/icons/close_primary.svg
  assets/icons/delete.svg
  assets/icons/file.svg
  assets/icons/gallery.svg
  assets/icons/make_photo.svg
  assets/icons/send.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/service/call.dart
  lib/store/chat_rx.dart
  lib/themes.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/widget/round_button.dart
  lib/ui/page/home/page/chat/component/attachment_selector.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/back_button.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/widget/animated_typing.dart
  lib/ui/page/home/widget/app_bar.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/popup_call/controller.dart
  lib/ui/page/style/tab/element.dart
  lib/ui/widget/text_field.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_reply_message_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#182 Disabling all incoming video makes some videos to stuck (#179)
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
Labels: enhancement, k::UI/UX

#96 Account `Call` size when determining initial secondary panel's size (#95)
  CHANGELOG.md
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/reorderable_fit.dart
Labels: enhancement, k::UI/UX

#183 Upgrade to 0.1.0-beta.7.2 backend
  .github/workflows/ci.yml
  dev/backend.toml
  docker-compose.yml
  lib/api/backend/extension/my_user.dart
  lib/api/backend/extension/user.dart
  lib/api/backend/graphql/fragments/UserAvatar.graphql
  lib/api/backend/graphql/fragments/UserCallCover.graphql
  lib/domain/model/avatar.dart
  lib/domain/model/user_call_cover.dart
  lib/store/my_user.dart
  lib/ui/page/home/page/my_profile/controller.dart
  schema.graphql
  test/unit/my_profile_gallery_test.dart
  test/widget/my_profile_gallery_test.dart
Labels: enhancement, k::deploy, k::refactor, k::toolchain

#145 Don't download file again if it's already downloaded (#141)
  assets/conf.toml
  lib/config.dart
  lib/domain/model/attachment.dart
  lib/domain/model/file.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/gallery.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/worker/call.dart
  lib/ui/worker/chat.dart
  lib/util/platform_utils.dart
  test/e2e/mock/platform_utils.dart
  test/mock/platform_utils.dart
  test/unit/chat_split_message_test.dart
  test/widget/chat_attachment_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#186 Bump up project version to 0.1.0-alpha.7
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#142 Redesign `Chat`s tab (#124)
  CHANGELOG.md
  assets/icons/chats.svg
  assets/icons/contacts.svg
  assets/icons/group.svg
  assets/icons/search.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/chat.dart
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/chat.dart
  lib/domain/service/call.dart
  lib/routes.dart
  lib/store/chat_rx.dart
  lib/themes.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/hovered_ink.dart
  lib/ui/page/home/tab/chats/widget/periodic_builder.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/worker/chat.dart
  pubspec.lock
  pubspec.yaml
  test/unit/date_time_to_short_test.dart
Labels: enhancement, k::UI/UX, k::refactor
