Repository team113/messenger, pull requests merged in 2022-07, with the labels that each got.

#7 Implement `User` GraphQL subscription (#4)
  CHANGELOG.md
  lib/api/backend/extension/user.dart
  lib/api/backend/graphql/fragments/BlacklistEventsVersioned.graphql
  lib/api/backend/graphql/fragments/UserEventsVersioned.graphql
  lib/api/backend/graphql/subscription/user/UserEvents.graphql
  lib/domain/repository/chat.dart
  lib/domain/repository/contact.dart
  lib/domain/repository/user.dart
  lib/domain/service/user.dart
  lib/provider/gql/components/user.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/contact_rx.dart
  lib/store/event/user.dart
  lib/store/my_user.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/add_contact_list_tile.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/user_search_bar/controller.dart
  lib/ui/page/home/widget/user_search_bar/view.dart
  test/e2e/configuration.dart
  test/e2e/features/user/subscription/.feature
  test/e2e/steps/go_to.dart
  test/e2e/steps/updates_bio.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::design, k::refactor

#26 New desktop call design
  CHANGELOG.md
  assets/audio/pop.mp3
  assets/icons/close.svg
  assets/icons/face.svg
  assets/icons/screen_share_small.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/precise_date_time/src/web.dart
  lib/domain/service/call.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/view.dart
  lib/ui/page/call/widget/animated_delayed_scale.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/call/widget/conditional_backdrop.dart
  lib/ui/page/call/widget/fit_view.dart
  lib/ui/page/call/widget/fit_wrap.dart
  lib/ui/page/call/widget/hint.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/overlay/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/popup_call/view.dart
  lib/ui/widget/svg/src/web.dart
  lib/ui/worker/call.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#34 Attach secondary view to nearest corner (#33)
  CHANGELOG.md
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX

#42 Fix horizontal scroll on `Home` page when vertical is going on (#41)
  CHANGELOG.md
  lib/ui/page/home/controller.dart
  lib/ui/page/home/view.dart
Labels: enhancement, k::UI/UX

#45 Fix GestureDetector drag down on mobile call (#44)
  CHANGELOG.md
  lib/ui/page/call/widget/minimizable_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX

#35 Redesign `Login` interface
  CHANGELOG.md
  assets/fonts/Roboto-Black.ttf
  assets/fonts/Roboto-BlackItalic.ttf
  assets/fonts/Roboto-Bold.ttf
  assets/fonts/Roboto-BoldItalic.ttf
  assets/fonts/Roboto-Italic.ttf
  assets/fonts/Roboto-Light.ttf
  assets/fonts/Roboto-LightItalic.ttf
  assets/fonts/Roboto-Medium.ttf
  assets/fonts/Roboto-MediumItalic.ttf
  assets/fonts/Roboto-Regular.ttf
  assets/fonts/Roboto-Thin.ttf
  assets/fonts/Roboto-ThinItalic.ttf
  assets/icons/visible_off.svg
  assets/icons/visible_on.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/provider/gql/exceptions.dart
  lib/provider/hive/application_settings.dart
  lib/routes.dart
  lib/themes.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  lib/ui/page/style/tab/element.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/outlined_rounded_button.dart
  lib/ui/widget/text_field.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/parameters/keys.dart
  test/widget/auth_test.dart
  test/widget/password_recovery_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#29 Redesign `Auth` page
  CHANGELOG.md
  assets/images/logo/logo.riv
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/config.dart
  lib/ui/page/auth/controller.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/page/settings/controller.dart
  lib/ui/page/home/page/settings/view.dart
  lib/ui/widget/selector.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/suite.dart
  test/widget/auth_test.dart
  test/widget/password_recovery_test.dart
Labels: enhancement, k::UI/UX, k::refactor
