Repository team113/messenger, pull requests merged in 2023-06, with the labels that each got.

#449 Fix `wakelock` invoking on Linux
  lib/ui/worker/call.dart
Labels: enhancement, k::refactor, platform::linux

#426 Refactor `HomeView` Page `user` `Widgets` functions to `Widget` classes
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/download_button.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/page/user/widget/blacklist_record.dart
  lib/ui/page/home/page/user/widget/name.dart
  lib/ui/page/home/page/user/widget/num.dart
  lib/ui/page/home/page/user/widget/presence.dart
  lib/ui/page/home/page/user/widget/status.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/widget/action.dart
  lib/ui/page/home/widget/field_button.dart
  lib/ui/page/home/widget/paddings.dart
  lib/ui/page/home/widget/unblock_button.dart
  macos/Podfile.lock
  test/e2e/features/home/chats/selection/.feature
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#448 Fix incorrect displaying `RaisedHand`
  lib/ui/page/call/widget/participant/widget.dart
Labels: enhancement, k::UI/UX

#445 Add desktop support for video playback (#438)
  .github/workflows/ci.yml
  CHANGELOG.md
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/main.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/desktop_controls.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/page/chat/widget/mobile_controls.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/chat/widget/video_progress_bar.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/src/interface.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/src/io.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/src/web.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/page/chat/widget/volume_bar.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::UI/UX, k::refactor

#412 Fix incorrect sorting local `Chat`-monolog (#406)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/chat.dart
  lib/domain/model/chat_item.dart
  lib/domain/repository/chat.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  test/e2e/features/chat/members/.feature
  test/e2e/features/chat/monolog/.feature
Labels: enhancement, k::UI/UX, k::refactor

#408 Implement handle 403 errors in `WebImage` (#344)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_gallery.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/chat/widget/web_image/src/non_web.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/util/log.dart
Labels: enhancement, k::UI/UX, k::refactor, platform::web

#451 Call status in `ChatCall` message
  Makefile
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/service/call.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/event/chat.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/style/tab/element.dart
  lib/util/media_utils.dart
  test/e2e/features/auth/create_account/.feature
Labels: enhancement, k::UI/UX, k::refactor

#453 Upgate `ChatCall` and `DataAttachment` design
  CHANGELOG.md
  assets/icons/arrow_down.svg
  assets/icons/call_audio.svg
  assets/icons/call_audio_blue.svg
  assets/icons/call_audio_red.svg
  assets/icons/call_video.svg
  assets/icons/call_video_blue.svg
  assets/icons/call_video_red.svg
  assets/icons/cancel.svg
  assets/icons/file.svg
  assets/icons/file_dark.svg
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/data_attachment.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#454 Low signal icon in call
  CHANGELOG.md
  assets/icons/low_signal_level.svg
  ios/Podfile.lock
  lib/domain/model/ongoing_call.dart
  lib/store/call.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/widget/participant/overlay.dart
  lib/ui/page/call/widget/participant/widget.dart
  macos/Podfile.lock
  test/e2e/steps/wait_until_attachment_fetched.dart
Labels: enhancement, k::UI/UX

#456 Update monolog icon and name
  CHANGELOG.md
  assets/icons/notes.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/main.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/widget/avatar.dart
Labels: enhancement, k::UI/UX, k::refactor

#443 Update `status` and `mute chats` context menus
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/themes.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/tab/chats/more/controller.dart
  lib/ui/page/home/tab/chats/more/view.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/widget/context_menu/menu.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/selector.dart
  test/e2e/configuration.dart
  test/e2e/features/home/mute/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/right_click_widget.dart
Labels: enhancement, k::UI/UX, k::refactor

#411 Refactor `CallView` `Elements` `Widget` functions to `Widget` classes
  lib/ui/page/auth/view.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/widget/message_info/view.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/blacklist/view.dart
  lib/ui/page/home/page/my_profile/call_window_switch/view.dart
  lib/ui/page/home/page/my_profile/camera_switch/view.dart
  lib/ui/page/home/page/my_profile/language/view.dart
  lib/ui/page/home/page/my_profile/link_details/view.dart
  lib/ui/page/home/page/my_profile/microphone_switch/view.dart
  lib/ui/page/home/page/my_profile/output_switch/view.dart
  lib/ui/page/home/page/my_profile/password/view.dart
  lib/ui/page/home/page/my_profile/timeline_switch/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/login/view.dart
  lib/ui/widget/floating_snack_bar.dart
  lib/ui/widget/member_tile.dart
  lib/ui/widget/modal_popup.dart
  lib/util/message_popup.dart
Labels: enhancement, k::refactor

#457 Chat optimization
  lib/main.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/attachment_selector.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::performance, k::refactor

#462 Active status (#418)
  CHANGELOG.md
  lib/domain/service/notification.dart
  lib/routes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/text_field.dart
  lib/util/platform_utils.dart
  test/e2e/mock/platform_utils.dart
  test/mock/platform_utils.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/password_recovery_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#467 Chat items highlighting
  CHANGELOG.md
  lib/themes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
Labels: enhancement, k::UI/UX, k::refactor

#430 Refactor `TabView` `Widgets` functions to `Widget` classes
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/hovered_ink.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/chats/widget/rectangular_call_button.dart
  lib/ui/page/home/tab/chats/widget/unread_counter.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/tab/menu/widget/menu_button.dart
  lib/ui/page/home/widget/bottom_padded_row.dart
  lib/ui/page/home/widget/shadowed_rounded_button.dart
Labels: enhancement, k::refactor
