Repository team113/messenger, pull requests merged in 2023-03, with the labels that each got.

#359 Implement favorite `Chat`s reordering (#354)
  CHANGELOG.md
  lib/themes.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/chat_tile.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/favorite/.feature
  test/e2e/steps/drag_chat.dart
Labels: enhancement, feature, k::UI/UX, k::refactor

#357 Rephrase `ChatInfo` messages
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/widget/back_button.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/worker/chat.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/avatar/.feature
  test/e2e/steps/see_chat_avatar.dart
Labels: enhancement, k::UI/UX, k::refactor

#270 Persist and use positions and sizes of `Call`s (#264)
  CHANGELOG.md
  lib/domain/model_type_id.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/call_rect.dart
  lib/routes.dart
  lib/store/settings.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  lib/util/web/web_utils.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#362 Refactor styles to use `SFDisplay` font
  CHANGELOG.md
  assets/fonts/Roboto-Black.ttf
  assets/fonts/Roboto-BlackItalic.ttf
  assets/fonts/Roboto-Bold.ttf
  assets/fonts/Roboto-BoldItalic.ttf
  assets/fonts/Roboto-Italic.ttf
  assets/fonts/Roboto-Light.ttf
  assets/fonts/Roboto-LightItalic.ttf
  assets/fonts/Roboto-Medium.ttf
  assets/fonts/Roboto-MediumItalic.ttf
  assets/fonts/Roboto-Regular.ttf
  assets/fonts/Roboto-Thin.ttf
  assets/fonts/Roboto-ThinItalic.ttf
  assets/fonts/SFUIDisplay-Bold.ttf
  assets/fonts/SFUIDisplay-Light.ttf
  assets/fonts/SFUIDisplay-Regular.ttf
  assets/icons/arrow_down.svg
  assets/icons/cancel.svg
  lib/domain/model/ongoing_call.dart
  lib/themes.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/data_attachment.dart
  lib/ui/page/home/page/my_profile/camera_switch/view.dart
  lib/ui/page/home/page/my_profile/microphone_switch/view.dart
  lib/ui/page/home/page/my_profile/output_switch/view.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/rectangle_button.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/selected_tile.dart
  lib/ui/widget/text_field.dart
  lib/util/platform_utils.dart
  macos/Runner/Base.lproj/MainMenu.xib
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor

#356 Scale secondary panel proportionally in `Call` (#258)
  CHANGELOG.md
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/reorderable_fit.dart
Labels: enhancement, k::UI/UX, k::refactor

#375 Smooth increase of incoming call ringtone (#367)
  CHANGELOG.md
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/worker/call.dart
  test/e2e/features/chat/members/.feature
  test/e2e/steps/tap_search_result.dart
Labels: enhancement, k::UI/UX

#118 Add ability to select text in message (#17)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/message_info/view.dart
  lib/ui/page/home/page/chat/widget/selection_text.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/copyable.dart
  lib/ui/page/home/page/my_profile/widget/download_button.dart
  lib/ui/page/home/tab/chats/more/view.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/sharable.dart
  lib/ui/widget/context_menu/menu.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/text_field.dart
  lib/util/platform_utils.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/copying/.feature
  test/e2e/mock/platform_utils.dart
  test/e2e/parameters/keys.dart
  test/e2e/steps/select_text.dart
  test/e2e/steps/tap_message.dart
  test/e2e/steps/tap_search_result.dart
Labels: enhancement, k::UI/UX, k::refactor

#380 Delete appearance of change password view when password is setting (#377)
  CHANGELOG.md
  lib/ui/page/home/page/my_profile/password/controller.dart
  lib/ui/page/home/page/my_profile/password/view.dart
Labels: enhancement, k::UI/UX, k::refactor
