Repository team113/messenger, pull requests merged in 2023-12, with the labels that each got.

#736 Move options in `AppBar` (#719)
  CHANGELOG.md
  assets/icons/forward_disabled.svg
  assets/icons/leave_group.svg
  assets/icons/report.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_subtitle.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/widget/svg/svgs.dart
  test/e2e/features/chat/clear/.feature
  test/e2e/features/chat/monolog/.feature
  test/e2e/features/user/blacklist/.feature
  test/e2e/parameters/keys.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#739 Change store get methods return type to `FutureOr <T>` (#673)
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/chat.dart
  lib/domain/repository/user.dart
  lib/domain/service/call.dart
  lib/domain/service/chat.dart
  lib/domain/service/user.dart
  lib/store/blocklist.dart
  lib/store/chat.dart
  lib/store/contact_rx.dart
  lib/store/my_user.dart
  lib/store/pagination/graphql.dart
  lib/store/pagination/hive.dart
  lib/store/pagination/hive_graphql.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/info/add_member/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/message_info/controller.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/worker/call.dart
Labels: enhancement, k::refactor

#744 Fix pagination issues (#216)
  lib/domain/model/chat.dart
  lib/store/chat.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  test/unit/chat_hide_test.dart
  test/widget/chat_hide_test.dart
Labels: enhancement, k::refactor

#757 Redesign `ContextMenu` on Desktop to display `SvgIcon`s
  CHANGELOG.md
  assets/fonts/NotoSansDisplay-Bold.ttf
  assets/fonts/NotoSansDisplay-Regular.ttf
  assets/fonts/Roboto-Bold.ttf
  assets/fonts/Roboto-Regular.ttf
  assets/icons/add_contact_white.svg
  assets/icons/block.svg
  assets/icons/block_white.svg
  assets/icons/clean_history_white.svg
  assets/icons/copy19.svg
  assets/icons/copy19_white.svg
  assets/icons/copy_18.svg
  assets/icons/delete19.svg
  assets/icons/delete19_white.svg
  assets/icons/delete_contact_white.svg
  assets/icons/download19.svg
  assets/icons/download19_white.svg
  assets/icons/edit.svg
  assets/icons/edit_white.svg
  assets/icons/favorite_small_white.svg
  assets/icons/forward_small_white.svg
  assets/icons/group_white.svg
  assets/icons/info.svg
  assets/icons/info_white.svg
  assets/icons/leave_group_white.svg
  assets/icons/mute_small_white.svg
  assets/icons/reply.svg
  assets/icons/reply_white.svg
  assets/icons/select.svg
  assets/icons/select_white.svg
  assets/icons/send_small.svg
  assets/icons/send_small_white.svg
  assets/icons/unfavorite_small_white.svg
  assets/icons/unmute_small_white.svg
  lib/themes.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/style/page/icons/view.dart
  lib/ui/page/style/page/typography/view.dart
  lib/ui/widget/context_menu/menu.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/worker/call.dart
  macos/Podfile.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#746 Ensure Sentry integration is tuned properly (#373)
  .github/workflows/ci.yml
  .gitignore
  Makefile
  ios/Podfile.lock
  lib/config.dart
  lib/domain/service/notification.dart
  lib/main.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/widget/modal_popup.dart
  lib/util/log.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, feature, k::config, k::monitoring, k::refactor, k::toolchain

#761 Bump up project version to 0.1.0-alpha.11.1
  .github/workflows/ci.yml
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement, k::toolchain

#763 Fix `Restore` button displayed with incorrect position on mobile (#758)
  CHANGELOG.md
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
Labels: enhancement, k::UI/UX

#762 Add `url` parameter to `sentry.upload` Makefile command
  .github/workflows/ci.yml
  Makefile
Labels: enhancement, k::toolchain

#750 Implement change `CallButtonsPosition` (#718)
  CHANGELOG.md
  assets/icons/chat_audio_call_disabled.svg
  assets/icons/chat_video_call_disabled.svg
  assets/icons/make_audio_call_disabled.svg
  assets/icons/make_audio_call_white.svg
  assets/icons/make_video_call_disabled.svg
  assets/icons/make_video_call_white.svg
  assets/images/media_buttons/app_bar.jpg
  assets/images/media_buttons/bottom.jpg
  assets/images/media_buttons/context_menu.jpg
  assets/images/media_buttons/more.jpg
  assets/images/media_buttons/top.jpg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/domain/model_type_id.dart
  lib/domain/repository/chat.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/application_settings.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/settings.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/widget/buttons.dart
  lib/ui/page/home/page/chat/message_field/widget/chat_button.dart
  lib/ui/page/home/page/chat/message_field/widget/more_button.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/circle_button.dart
  lib/ui/page/home/page/my_profile/call_buttons_switch/controller.dart
  lib/ui/page/home/page/my_profile/call_buttons_switch/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
  lib/ui/widget/context_menu/menu.dart
  lib/ui/widget/svg/svgs.dart
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#756 Generate name for StorageFile based on its mime type (#726)
  CHANGELOG.md
  analysis_options.yaml
  lib/domain/model/file.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/gallery_popup.dart
Labels: enhancement, k::UI/UX
