Repository team113/messenger, pull requests merged in 2023-09, with the labels that each got.

#532 Don't make GraphQL calls when `hasPrevious` is known in `HiveGraphQlPageProvider` (#527)
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/chat.dart
  lib/domain/repository/settings.dart
  lib/provider/gql/exceptions.dart
  lib/provider/hive/base.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/contact.dart
  lib/store/pagination.dart
  lib/store/pagination/hive.dart
  lib/themes.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/page/login/controller.dart
Labels: enhancement, k::refactor

#543 Bump up project version to 0.1.0-alpha.9.4
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#587 Display UserNum formatted as quartets
  CHANGELOG.md
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/domain/model/user.dart
  lib/domain/service/contact.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/call/widget/participant/overlay.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/chat_subtitle.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/page/user/widget/name.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/chats/widget/search_user_tile.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/widget/contact_tile.dart
  lib/ui/page/home/widget/num.dart
  lib/ui/widget/member_tile.dart
  lib/ui/worker/background/src/main.dart
  lib/ui/worker/call.dart
  lib/ui/worker/chat.dart
  macos/Podfile.lock
Labels: enhancement, k::UI/UX

#591 Update Contribution Guide to reflect backend connectivity
  CONTRIBUTING.md
  ios/Podfile.lock
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/widget/user_profile_test.dart
Labels: k::documentation, enhancement

#301 Do not mirror local video when environment camera is used (#70)
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/widget/participant/widget.dart
  lib/ui/page/call/widget/video_view.dart
Labels: enhancement, k::UI/UX

#423 Improve attachments downloading (#140)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/attachment.dart
  lib/domain/model/native_file.dart
  lib/domain/service/notification.dart
  lib/main.dart
  lib/provider/hive/download.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/data_attachment.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/page/chat/widget/video/video.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/worker/cache.dart
  lib/ui/worker/call.dart
  lib/ui/worker/chat.dart
  lib/util/obs/rxmap.dart
  lib/util/platform_utils.dart
  test/e2e/mock/platform_utils.dart
  test/e2e/parameters/download_status.dart
  test/e2e/steps/wait_until_file_status.dart
  test/mock/platform_utils.dart
  test/unit/cache_worker_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#597 Redesign icons on `Work` page
  CHANGELOG.md
  assets/icons/freelance.svg
  assets/icons/freelance_white.svg
  assets/icons/frontend.svg
  assets/icons/frontend_white.svg
  assets/icons/rust.svg
  assets/icons/rust_white.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/routes.dart
  lib/ui/page/home/page/my_profile/blacklist/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/work/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/work/page/freelance/controller.dart
  lib/ui/page/work/page/freelance/view.dart
  lib/ui/page/work/page/frontend/view.dart
  lib/ui/page/work/widget/source_block.dart
  lib/ui/page/work/widget/vacancy_button.dart
  lib/ui/widget/menu_button.dart
  test/e2e/features/profile/l10n/.feature
  web/index.html
Labels: enhancement, k::UI/UX

#599 Fix ContextMenu called twice longpressing on element (#508)
  CHANGELOG.md
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/widget/context_menu/region.dart
Labels: enhancement, k::UI/UX

#592 Вдавленный текст. Сделать виджет, создающий эффект вдавленного текста
  lib/ui/widget/inner_shadow.dart
Labels: enhancement, k::UI/UX

#604 Fix flashing background SVG on web (#549)
  CHANGELOG.md
  lib/provider/gql/components/user.dart
  lib/store/auth.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/overlay/view.dart
  lib/ui/page/home/view.dart
  test/e2e/mock/graphql.dart
Labels: enhancement, k::UI/UX, platform::web

#612 Fix `AnimatedSwitcher`s throwing `Duplicate keys found` (#386)
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/widget/participant/overlay.dart
  lib/ui/page/call/widget/participant/widget.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/data_attachment.dart
  lib/ui/page/home/page/chat/widget/message_info/view.dart
  lib/ui/page/home/page/chat/widget/video/video.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/rectangle_button.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/widget/animated_switcher.dart
  lib/ui/widget/member_tile.dart
  lib/ui/widget/selected_dot.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::refactor

#616 Redesign `Colors` tab on `Style` page (#614)
  CHANGELOG.md
  assets/icons/dark_mode.svg
  assets/icons/light_mode.svg
  assets/icons/palette.svg
  assets/icons/typography.svg
  assets/icons/widgets.svg
  lib/themes.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/widget/back_button.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/video/widget/position.dart
  lib/ui/page/home/tab/chats/widget/rectangular_call_button.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/page/style/controller.dart
  lib/ui/page/style/page/colors/view.dart
  lib/ui/page/style/page/colors/widget/color_schema.dart
  lib/ui/page/style/page/typography/view.dart
  lib/ui/page/style/page/widgets/view.dart
  lib/ui/page/style/page/widgets/widget/playable_asset.dart
  lib/ui/page/style/page/widgets/widget/subtitle_container.dart
  lib/ui/page/style/view.dart
  lib/ui/page/style/widget/style_card.dart
  lib/util/fixed_digits.dart
  test/e2e/features/contact/favorite/.feature
  test/e2e/features/home/contacts/selection/.feature
Labels: enhancement, k::UI/UX, k::refactor

#521 Cover `Hive.clean` version mismatch with E2E test (#503)
  lib/config.dart
  lib/main.dart
  test/e2e/configuration.dart
  test/e2e/features/cache/.feature
  test/e2e/features/contact/favorite/.feature
  test/e2e/steps/update_app_version.dart
Labels: enhancement, k::testing
