Repository team113/messenger, pull requests merged in 2023-02, with the labels that each got.

#336 Redesign copied message popup
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/routes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/copyable.dart
  lib/ui/page/home/tab/chats/more/view.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/sharable.dart
  lib/ui/widget/floating_snack_bar.dart
  lib/ui/worker/window.dart
  lib/util/message_popup.dart
  lib/util/platform_utils.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX

#324 Image disappearing on upload (#21)
  lib/domain/model/native_file.dart
  lib/provider/hive/chat.dart
  lib/provider/hive/chat_item.dart
  lib/provider/hive/draft.dart
  lib/store/chat.dart
  lib/store/my_user.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/gallery.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#321 Refactor subscriptions to properly reconnect (#66)
  Makefile
  lib/domain/model/attachment.dart
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/call.dart
  lib/domain/repository/chat.dart
  lib/domain/service/call.dart
  lib/domain/service/chat.dart
  lib/main.dart
  lib/provider/gql/base.dart
  lib/provider/gql/components/call.dart
  lib/provider/gql/components/chat.dart
  lib/provider/gql/components/contact.dart
  lib/provider/gql/components/user.dart
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/contact.dart
  lib/store/my_user.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/worker/background/src/main.dart
  lib/util/backoff.dart
  lib/util/platform_utils.dart
  lib/util/stream_utils.dart
  test/mock/graphql_provider.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/contact_rename_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_gallery_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#347 Redesign screen sharing modal
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/store/call.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/screen_share/controller.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/field_button.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/widget/floating_snack_bar.dart
  lib/util/message_popup.dart
Labels: enhancement, k::UI/UX, k::refactor

#335 Implement `ChatItem` info modal (#330)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/chat_item_reads.dart
  lib/ui/page/home/page/chat/widget/message_info/controller.dart
  lib/ui/page/home/page/chat/widget/message_info/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/app_bar.dart
  lib/ui/widget/text_field.dart
Labels: feature, k::UI/UX, k::refactor

#342 Add `MyUser.unreadChatsCount` badge to Windows (#327)
  CHANGELOG.md
  assets/icons/notification/1.ico
  assets/icons/notification/2.ico
  assets/icons/notification/3.ico
  assets/icons/notification/4.ico
  assets/icons/notification/5.ico
  assets/icons/notification/6.ico
  assets/icons/notification/7.ico
  assets/icons/notification/8.ico
  assets/icons/notification/9+.ico
  assets/icons/notification/9.ico
  lib/ui/worker/chat.dart
  lib/ui/worker/my_user.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::UI/UX, platform::windows

#343 Fix E2E tests failing (#339)
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/contact.dart
  lib/store/my_user.dart
  lib/store/user_rx.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/widget/minimizable_view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/animated_fab.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/animated_slider.dart
  lib/ui/page/home/widget/animated_typing.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/widget/allow_overflow.dart
  lib/ui/widget/animations.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/text_field.dart
  lib/util/stream_utils.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/configuration.dart
  test/e2e/features/auth/create_account/.feature
  test/e2e/hook/reset_app.dart
  test/e2e/suite.dart
Labels: enhancement, k::refactor, k::testing

#351 Fix some bugs & problems
  assets/icons/chat.svg
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/chat.dart
  lib/routes.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/password/controller.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/menu/view.dart
  test/unit/chat_read_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#350 Redesign loaders (#345)
  CHANGELOG.md
  assets/images/logo/head.riv
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/application_settings.dart
  lib/routes.dart
  lib/store/settings.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/chat_direct_link/view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/add_member/view.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/desktop_controls.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/page/chat/widget/mobile_controls.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/page/popup_call/view.dart
  lib/ui/widget/progress_indicator.dart
  test/e2e/configuration.dart
  test/e2e/features/home/introduction/.feature
  test/e2e/features/home/logout/.feature
  test/e2e/features/my_user/online_status/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/scroll_until.dart
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor
