Repository team113/messenger, pull requests merged in 2023-08, with the labels that each got.

#505 Replace `tabularFigures` with `FixedDigitsExtension` (#504)
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/tab/chats/widget/rectangular_call_button.dart
Labels: enhancement, k::UI/UX

#507 Implement `MultimediaView` in `StyleView`
  lib/ui/page/auth/widget/animated_logo.dart
  lib/ui/page/home/widget/animated_typing.dart
  lib/ui/page/style/page/colors/view.dart
  lib/ui/page/style/page/multimedia/view.dart
  lib/ui/page/style/page/multimedia/widget/playable_asset.dart
  lib/ui/page/style/page/multimedia/widget/subtitle_container.dart
  lib/ui/page/style/page/typography/view.dart
  lib/ui/page/style/view.dart
  lib/ui/page/style/widget/header.dart
  lib/ui/page/style/widget/scrollable_column.dart
  web/index.html
Labels: enhancement, k::refactor

#425 Refactor `HomeView` Page `my_profile` `Widgets` functions to `Widget` classes
  lib/themes.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/background_preview.dart
  lib/ui/page/home/page/my_profile/widget/dropdown.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/page/home/page/my_profile/widget/name.dart
  lib/ui/page/home/page/my_profile/widget/status.dart
  lib/ui/page/home/page/my_profile/widget/switch_field.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/home/widget/field_button.dart
  lib/ui/page/home/widget/num.dart
  lib/ui/page/login/view.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::refactor

#506 Refactor ContextMenuRegion to display ContextMenu with fading effect (#499)
  CHANGELOG.md
  lib/ui/widget/context_menu/menu_overlay.dart
  lib/ui/widget/context_menu/region.dart
Labels: enhancement, k::refactor

#492 Windows local notifications (#439)
  CHANGELOG.md
  assets/conf.toml
  assets/icons/app_icon.ico
  lib/config.dart
  lib/domain/service/notification.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/time_label.dart
  lib/ui/page/home/tab/chats/widget/unread_counter.dart
  lib/util/platform_utils.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/mock/platform_utils.dart
  test/mock/platform_utils.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::UI/UX, platform::windows

#516 Update `TextFieldState` validating logic (#501)
  ios/Podfile
  ios/Podfile.lock
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  lib/ui/widget/text_field.dart
  macos/Podfile
  macos/Podfile.lock
  test/unit/text_field_state_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#513 Highlight profile Block on MenuButton press (#385)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/page/home/widget/highlighted_container.dart
Labels: enhancement, k::UI/UX, k::refactor

#520 Upgrade Flutter to 3.13 version
  .github/workflows/ci.yml
  android/build.gradle
  ios/Podfile.lock
  lib/domain/model/attachment.dart
  lib/provider/gql/base.dart
  lib/provider/gql/components/chat.dart
  lib/provider/gql/components/user.dart
  lib/routes.dart
  lib/store/chat.dart
  lib/store/my_user.dart
  lib/themes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/widget/video/video.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/widget/lifecycle_observer.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pubspec.lock
  pubspec.yaml
  test/mock/route_information_provider.dart
Labels: enhancement, k::refactor, k::toolchain, k::dependencies

#417 Add images caching (#140)
  .gitignore
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/Podfile.lock
  lib/domain/model/cache_info.dart
  lib/domain/model_type_id.dart
  lib/main.dart
  lib/provider/hive/cache.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/worker/cache.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
  pubspec.lock
  test/e2e/hook/reset_app.dart
  test/e2e/mock/platform_utils.dart
  test/mock/platform_utils.dart
  test/unit/cache_worker_test.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, feature, k::UI/UX, k::refactor

#522 Cancel `keepOnline` when app is not active
  CHANGELOG.md
  lib/store/my_user.dart
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#526 Refactor `GalleryPopup` to use `RetryImage` instead of `NetworkImage`s (#524)
  lib/ui/page/home/widget/gallery_popup.dart
Labels: enhancement, k::refactor, platform::android, platform::ios

#523 Replace `flutter_meedu_videoplayer` with `media_kit` videoplayer (#473)
  lib/domain/model/native_file.dart
  lib/main.dart
  lib/ui/page/home/page/chat/widget/video/video.dart
  lib/ui/page/home/page/chat/widget/video/widget/centered_play_pause.dart
  lib/ui/page/home/page/chat/widget/video/widget/custom_play_pause.dart
  lib/ui/page/home/page/chat/widget/video/widget/desktop_controls.dart
  lib/ui/page/home/page/chat/widget/video/widget/mobile_controls.dart
  lib/ui/page/home/page/chat/widget/video/widget/position.dart
  lib/ui/page/home/page/chat/widget/video/widget/video_progress_bar.dart
  lib/ui/page/home/page/chat/widget/video/widget/video_volume_bar.dart
  lib/ui/page/home/page/chat/widget/video/widget/volume_button.dart
  lib/ui/page/home/page/chat/widget/video/widget/volume_overlay.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/src/interface.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/src/io.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/src/web.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/gallery_popup.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::refactor

#517 Implement `Hive` pagination in chat (#216)
  lib/domain/model/precise_date_time/src/web.dart
  lib/domain/repository/chat.dart
  lib/provider/hive/base.dart
  lib/provider/hive/chat_item.dart
  lib/store/chat_rx.dart
  lib/store/pagination.dart
  lib/store/pagination/graphql.dart
  lib/store/pagination/hive.dart
  lib/store/pagination/hive_graphql.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/widget/menu_interceptor/src/web.dart
  test/e2e/features/chat/sending_status/messages.feature
  test/unit/pagination_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, k::refactor

#529 Redesign Badges in CustomNavigationBar (#500)
  .github/workflows/ci.yml
  CHANGELOG.md
  lib/themes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/page/style/page/typography/view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#531 Fix monolog e2e timeout exception (#514)
  lib/ui/page/call/component/desktop.dart
  web/index.html
Labels: enhancement, k::refactor

#410 Refactor `CallView` components `Widget` functions to `Widget` classes
  lib/themes.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/widget/animated_participant.dart
  lib/ui/page/call/widget/call_button.dart
  lib/ui/page/call/widget/chat_info_card.dart
  lib/ui/page/call/widget/description_child.dart
  lib/ui/page/call/widget/dock_decorator.dart
  lib/ui/page/call/widget/drop_box.dart
  lib/ui/page/call/widget/drop_box_area.dart
  lib/ui/page/call/widget/launchpad.dart
  lib/ui/page/call/widget/participant/overlay.dart
  lib/ui/page/call/widget/title_bar.dart
  lib/ui/page/style/page/colors/view.dart
  lib/ui/widget/context_menu/mobile.dart
Labels: enhancement, k::refactor
