Repository team113/messenger, pull requests merged in 2023-05, with the labels that each got.

#409 Refactor `AuthView` `Widget` functions to `Widget` classes
  assets/images/logo/logo.riv
  lib/ui/page/auth/controller.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/auth/widget/animated_logo.dart
  lib/ui/page/auth/widget/cupertino_button.dart
Labels: enhancement, k::refactor

#392 Display `Chat`s with `OngoingCall`s above favorite `Chat`s (#371)
  CHANGELOG.md
  lib/store/chat.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#431 Upgrade Flutter to 3.10 version
  .github/workflows/ci.yml
  android/app/build.gradle
  android/build.gradle
  ios/Podfile.lock
  lib/domain/service/notification.dart
  lib/provider/gql/components/auth.dart
  lib/provider/gql/components/call.dart
  lib/provider/gql/components/chat.dart
  lib/provider/gql/components/contact.dart
  lib/provider/gql/components/user.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/widget/animated_cliprrect.dart
  lib/ui/page/call/widget/conditional_backdrop.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/widget/safe_scrollbar.dart
  lib/ui/widget/selector.dart
  lib/ui/worker/call.dart
  lib/util/obs/rxsplay.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: enhancement, k::refactor, k::toolchain, k::dependencies

#346 Refactor `OngoingCall` to use `MediaUtils`
  .gitignore
  lib/domain/model/ongoing_call.dart
  lib/domain/service/auth.dart
  lib/domain/service/notification.dart
  lib/provider/hive/base.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/screen_share/controller.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/widget/minimizable_view.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/my_profile/camera_switch/controller.dart
  lib/ui/page/home/page/my_profile/camera_switch/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/view.dart
  lib/ui/page/home/page/my_profile/output_switch/controller.dart
  lib/ui/page/home/page/my_profile/output_switch/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/worker/call.dart
  lib/util/log.dart
  lib/util/media_utils.dart
  lib/util/pubspec_builder.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor

#436 Fix links parsing (#429)
  CHANGELOG.md
  lib/ui/page/home/page/chat/widget/chat_item.dart
  test/unit/parse_links_test.dart
  windows/runner/Runner.rc
Labels: enhancement, k::UI/UX

#433 Refactor `LoginView` `Widgets` functions to `Widget` classes
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/my_profile/blacklist/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/copyable.dart
  lib/ui/page/home/page/my_profile/widget/field_button.dart
  lib/ui/page/home/tab/chats/more/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/page/home/widget/safe_scrollbar.dart
  lib/ui/page/home/widget/sharable.dart
  lib/ui/page/login/view.dart
  lib/ui/page/login/widget/primary_button.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/floating_snack_bar.dart
Labels: enhancement, k::refactor

#416 Update messages design
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/l10n/l10n.dart
  lib/store/chat_rx.dart
  lib/themes.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/data_attachment.dart
  lib/ui/page/home/page/chat/widget/message_info/view.dart
  lib/ui/page/home/page/chat/widget/message_timestamp.dart
  lib/ui/page/home/page/chat/widget/selection_text.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/style/tab/color.dart
  test/unit/date_time_to_short_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#437 Disable media buttons in Chrome (#401)
  CHANGELOG.md
  assets/audio/chinese-web.mp3
  assets/audio/chinese.mp3
  assets/audio/ringing.mp3
  lib/ui/worker/call.dart
Labels: enhancement, k::UI/UX

#440 Add navigation buttons animation
  CHANGELOG.md
  assets/icons/chats.svg
  assets/icons/chats_muted.svg
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/animated_button.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/page/home/widget/retry_image.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/steps/see_chat_avatar.dart
Labels: enhancement, k::UI/UX, k::refactor

#419 Refactor `CallView` `Widget` functions to `Widget` classes
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/widget/animated_delayed_scale.dart
  lib/ui/page/call/widget/animated_delayed_width.dart
  lib/ui/page/call/widget/call_title.dart
  lib/ui/page/call/widget/conditional_backdrop.dart
  lib/ui/page/call/widget/dock.dart
  lib/ui/page/call/widget/fit_wrap.dart
  lib/ui/page/call/widget/floating_fit/view.dart
  lib/ui/page/call/widget/hint.dart
  lib/ui/page/call/widget/minimizable_view.dart
  lib/ui/page/call/widget/participant/decorator.dart
  lib/ui/page/call/widget/participant/overlay.dart
  lib/ui/page/call/widget/participant/widget.dart
  lib/ui/page/call/widget/raised_hand.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/call/widget/scaler.dart
  lib/ui/page/call/widget/tooltip_button.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
Labels: enhancement, k::refactor
