Repository team113/messenger, pull requests merged in 2023-01, with the labels that each got.

#274 Persist and use window's size and position (#263)
  CHANGELOG.md
  lib/domain/model_type_id.dart
  lib/main.dart
  lib/provider/hive/window.dart
  lib/store/model/window_preferences.dart
  lib/ui/worker/window.dart
  lib/util/platform_utils.dart
  linux/my_application.cc
  macos/Runner/MainFlutterWindow.swift
  windows/runner/win32_window.cpp
Labels: enhancement, k::UI/UX

#287 Redesign mobile `Call` UI (#282)
  CHANGELOG.md
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/fit_view.dart
  lib/ui/page/call/widget/swappable_fit.dart
Labels: enhancement, k::UI/UX, k::refactor

#289 Fix draft bug
  lib/ui/page/home/page/chat/view.dart
Labels: enhancement, k::refactor

#247 Refactor and redesign group creating on `Chat`s tab (#238)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/routes.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/selected_user_tile.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/navigation_bar.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_leave_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#294 Change background light svg (#273)
  assets/images/background_light.svg
Labels: enhancement, k::UI/UX

#255 Add read indicators to `Chat`-groups (#253)
  CHANGELOG.md
  lib/domain/repository/chat.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/chat_item_reads.dart
  lib/ui/page/home/tab/chats/create_group/controller.dart
  lib/ui/page/home/tab/chats/create_group/view.dart
  lib/ui/page/home/tab/chats/widget/selected_user_tile.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_edit_message_test.dart
Labels: enhancement, k::UI/UX

#297 Add delay to `ChatItem`s replying (#284)
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
Labels: enhancement, k::UI/UX, k::refactor

#298 Add subscription for `RxUser` from `Chat`-dialog
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
Labels: enhancement, k::refactor

#293 Redesign `Call` settings (#283)
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/home/page/my_profile/camera_switch/controller.dart
  lib/ui/page/home/page/my_profile/camera_switch/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/view.dart
  lib/ui/page/home/page/my_profile/output_switch/controller.dart
  lib/ui/page/home/page/my_profile/output_switch/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#285 Implement favorite `Contact`s reordering (#269)
  CHANGELOG.md
  lib/store/contact.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/app_bar.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/contact_tile.dart
  lib/ui/page/home/widget/navigation_bar.dart
  test/e2e/configuration.dart
  test/e2e/features/contact/favorite/.feature
  test/e2e/steps/drag_contact.dart
  test/e2e/steps/see_contact_position.dart
Labels: enhancement, k::UI/UX, k::refactor

#300 Make secondary panel rounded in `Call` (#292)
  CHANGELOG.md
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
Labels: enhancement, k::UI/UX, k::refactor

#276 Add `Scrollbar`s to mobile (#262)
  CHANGELOG.md
  lib/themes.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/blacklist/controller.dart
  lib/ui/page/home/page/my_profile/blacklist/view.dart
  lib/ui/page/home/page/my_profile/language/controller.dart
  lib/ui/page/home/page/my_profile/language/view.dart
  lib/ui/page/home/page/my_profile/password/controller.dart
  lib/ui/page/home/page/my_profile/password/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/home/tab/menu/status/controller.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/user_search_bar/controller.dart
  lib/ui/page/home/widget/user_search_bar/view.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#288 Implement `MyUser` mutting and unmutting (#278)
  CHANGELOG.md
  assets/icons/chats_muted.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/api/backend/graphql/mutation/user/ToggleMyUserMute.graphql
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/routes.dart
  lib/store/my_user.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/tab/chats/more/controller.dart
  lib/ui/page/home/tab/chats/more/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/worker/call.dart
  lib/ui/worker/chat.dart
  test/e2e/features/home/mute/.feature
  test/e2e/parameters/keys.dart
  test/unit/my_user_muting.dart
Labels: enhancement, feature, k::UI/UX

#313 Redesign status in `Menu` header
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/api/backend/graphql/mutation/contact/FavoriteChatContact.graphql
  lib/domain/repository/my_user.dart
  lib/domain/service/call.dart
  lib/provider/gql/components/contact.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/widget/modal_popup.dart
Labels: enhancement, k::UI/UX, k::refactor

#315 Fix iOS crashing due to `flutter_background_service`
  .github/workflows/ci.yml
  ios/.editorconfig
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/Runner.entitlements
Labels: enhancement, k::refactor, k::toolchain, platform::ios

#302 Display media prompt race (#108)
  lib/domain/model/ongoing_call.dart
Labels: enhancement, k::UI/UX

#316 Improve mobile `Call`-dialog UI (#311)
  CHANGELOG.md
  assets/icons/audio_call.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/call_title.dart
  lib/ui/page/call/widget/floating_fit/controller.dart
  lib/ui/page/call/widget/floating_fit/view.dart
  lib/ui/page/call/widget/round_button.dart
  lib/ui/widget/animated_delayed_switcher.dart
Labels: enhancement, k::UI/UX, k::refactor

#317 Add blacklist indicators to `User`s (#303)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/chat.dart
  lib/routes.dart
  lib/store/user.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/blacklist/controller.dart
  lib/ui/page/home/page/my_profile/blacklist/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/delete_account/controller.dart
  lib/ui/page/home/page/my_profile/delete_account/view.dart
  lib/ui/page/home/page/my_profile/delete_email/controller.dart
  lib/ui/page/home/page/my_profile/delete_email/view.dart
  lib/ui/page/home/page/my_profile/delete_phone/controller.dart
  lib/ui/page/home/page/my_profile/delete_phone/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/chats/widget/search_user_tile.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/util/message_popup.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#323 Redesign searching on `Contact`s and `Chat`s tabs (#304)
  CHANGELOG.md
  lib/ui/page/call/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/app_bar.dart
Labels: enhancement, k::UI/UX, k::refactor

#240 Update `User.dialog` when creating a `Chat`-dialog (#231)
  lib/domain/repository/user.dart
  lib/routes.dart
  lib/store/chat.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/widget/search_user_tile.dart
  lib/ui/page/home/tab/contacts/view.dart
Labels: enhancement, k::refactor

#211 Implement transparent color to system bar (#208)
  CHANGELOG.md
  android/app/src/main/kotlin/com/example/social_app/MainActivity.kt
  android/app/src/main/res/values/styles.xml
  assets/icons/muted_dark.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/provider/gql/exceptions.dart
  lib/themes.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/widget/floating_fit/view.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/app_bar.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/page/home/widget/safe_scrollbar.dart
  lib/ui/widget/outlined_rounded_button.dart
  test/widget/chat_hide_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#322 Replace `phone_numbers_parser` with `RegExp` (#314)
  lib/domain/model/user.dart
  lib/provider/gql/exceptions.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  pubspec.lock
  pubspec.yaml
  test/unit/my_user_muting_test.dart
  test/unit/phone_test.dart
  test/unit/toggle_chat_mute_test.dart
Labels: enhancement, k::refactor

#332 Redesign `Participant`s modal in `Call` (#328)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/participant/view.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/widget/contact_tile.dart
Labels: enhancement, k::UI/UX, k::refactor

#334 Implement automatic microphone switching
  ios/Podfile.lock
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  pubspec.lock
  pubspec.yaml
  windows/runner/resources/app_icon.ico
Labels: enhancement, k::UI/UX, k::refactor

#337 Implement `ChatItem`s grouping in `Chat`
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/domain/model/ongoing_call.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/screen_share/controller.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/widget/animated_transition.dart
  lib/ui/page/call/widget/dock.dart
  lib/ui/page/call/widget/floating_fit/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/my_profile/camera_switch/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/controller.dart
  lib/ui/page/home/page/my_profile/output_switch/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/download_button.dart
  lib/ui/page/home/widget/confirm_dialog.dart
Labels: enhancement, k::UI/UX, k::refactor

#319 Improve desktop incoming/outgoing `Call` UI (#309)
  CHANGELOG.md
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/call/widget/floating_fit/controller.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/page/call/widget/round_button.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor
