Repository team113/messenger, pull requests merged in 2023-11, with the labels that each got.

#688 Use `ImageFile.height` when displaying `ImageAttachment`s (#653)
  CHANGELOG.md
  lib/domain/model/native_file.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/widget/retry_image.dart
Labels: enhancement, k::UI/UX

#659 Use `thumbhash` for `ImageFile`s previews (#645)
  build.yaml
  lib/api/backend/extension/file.dart
  lib/api/backend/graphql/fragments/ImageFile.graphql
  lib/api/backend/graphql/parsers/thumbhash.dart
  lib/domain/model/file.dart
  lib/domain/model/user_call_cover.dart
  lib/domain/model_type_id.dart
  lib/provider/hive/chat_item.dart
  lib/provider/hive/user.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_gallery.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/worker/cache.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#635 Local `Chat`s pagiantion (#605)
  lib/provider/gql/base.dart
  lib/provider/hive/base.dart
  lib/provider/hive/draft.dart
  lib/provider/hive/recent_chat.dart
  lib/routes.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/my_user.dart
  lib/store/pagination.dart
  lib/store/pagination/combined_pagination.dart
  lib/store/pagination/hive.dart
  lib/store/pagination/hive_graphql.dart
  lib/store/search.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/util/backoff.dart
  lib/util/stream_utils.dart
  test/e2e/configuration.dart
  test/e2e/features/pagination/chats/.feature
  test/e2e/steps/chats_availability.dart
  test/e2e/steps/has_group.dart
  test/e2e/steps/in_chat_with.dart
  test/e2e/steps/restart_app.dart
  test/e2e/steps/scroll_until.dart
  test/e2e/steps/see_chats.dart
  test/e2e/steps/text_field.dart
  test/e2e/world/custom_world.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#669 Bump up project version to 0.1.0-alpha.11
  CHANGELOG.md
  helm/messenger/Chart.yaml
  lib/store/pagination.dart
  pubspec.lock
  pubspec.yaml
Labels: k::documentation, enhancement, k::UI/UX

#696 Throttle `GraphQlProvider.subscribe`s (#678)
  lib/provider/gql/base.dart
  lib/util/rate_limiter.dart
  test/unit/rate_limiter_test.dart
Labels: enhancement, k::refactor

#702 Don't use `onActivityChanged` for `keepOnline` determination on desktop (#681)
  CHANGELOG.md
  lib/store/my_user.dart
Labels: enhancement, k::UI/UX, k::refactor

#711 Fix invalid `ChatCall.caller` name being displayed in `PopupCall`s
  CHANGELOG.md
  lib/util/web/web_utils.dart
Labels: enhancement, k::UI/UX

#716 Replace `ubuntu:latest` with `debian:bullseye` for Linux build CI job
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain, platform::linux

#703 Add single blue mark if not the whole Chat-group read message (#666)
  CHANGELOG.md
  assets/icons/half_read.svg
  assets/icons/half_read_white.svg
  lib/domain/model/chat.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/message_timestamp.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/monolog/.feature
  test/e2e/features/chat/sending_status/half_read.feature
  test/e2e/parameters/sending_status.dart
  test/e2e/steps/has_group.dart
  test/e2e/steps/reads_message.dart
  test/e2e/steps/wait_until_attachment_status.dart
  test/e2e/steps/wait_until_message_status.dart
Labels: enhancement, k::UI/UX

#724 Upgrade Flutter to 3.16 version
  .github/workflows/ci.yml
  ios/Podfile.lock
  lib/domain/model/attachment.dart
  lib/domain/model/chat.dart
  lib/domain/model/chat_call.dart
  lib/domain/model/chat_item.dart
  lib/domain/model/contact.dart
  lib/domain/model/my_user.dart
  lib/domain/model/session.dart
  lib/domain/model/user.dart
  lib/main.dart
  lib/provider/gql/exceptions.dart
  lib/store/event/contact.dart
  lib/store/model/chat_call.dart
  lib/store/model/chat_item.dart
  lib/store/model/contact.dart
  lib/store/model/my_user.dart
  lib/store/model/session_data.dart
  lib/store/model/user.dart
  lib/store/model/version.dart
  lib/themes.dart
  lib/ui/page/auth/widget/animated_logo.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/home/overlay/view.dart
  lib/ui/page/home/page/chat/widget/animated_offset.dart
  lib/ui/page/home/widget/avatar.dart
  lib/util/fixed_digits.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/e2e/features/chat/copying/.feature
  test/e2e/steps/select_text.dart
  test/e2e/steps/text_field.dart
  test/e2e/steps/users.dart
Labels: enhancement, k::dependencies

#707 Fix loader on incoming videos (#700)
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/widget/dock.dart
  lib/ui/page/call/widget/participant/widget.dart
  test/e2e/features/chat/copying/.feature
Labels: enhancement, k::UI/UX

#730 Add `Icons` tab to `Style` page (#710)
  CHANGELOG.md
  assets/icons/application/alert.png
  assets/icons/application/alert.zip
  assets/icons/application/android.png
  assets/icons/application/android.zip
  assets/icons/application/iOS.png
  assets/icons/application/iOS.zip
  assets/icons/application/macOS.png
  assets/icons/application/macOS.zip
  assets/icons/application/web.png
  assets/icons/application/web.zip
  assets/icons/application/windows.ico
  assets/icons/icons.svg
  lib/config.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/ui/page/style/controller.dart
  lib/ui/page/style/page/colors/view.dart
  lib/ui/page/style/page/icons/controller.dart
  lib/ui/page/style/page/icons/view.dart
  lib/ui/page/style/view.dart
  lib/ui/widget/context_menu/menu.dart
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#697 Add a save button to the context menu (#654)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/widget/context_menu/menu_overlay.dart
  lib/util/platform_utils.dart
Labels: enhancement, k::UI/UX, k::design
