Repository team113/messenger, pull requests merged in 2023-10, with the labels that each got.

#611 Fix double `Navigator.pop`ping of some modals (#67)
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/info/add_member/view.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/blacklist/view.dart
  lib/ui/page/home/page/my_profile/camera_switch/controller.dart
  lib/util/platform_utils.dart
Labels: enhancement, k::refactor

#643 Upgrade to 0.1.0-beta.11 backend version
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  dev/backend.toml
  docker-compose.yml
  lib/api/backend/extension/chat.dart
  lib/api/backend/graphql/fragments/ChatEventsVersioned.graphql
  lib/api/backend/graphql/mutation/chat/EditChatMessage.graphql
  lib/domain/model/chat_message_input.dart
  lib/domain/repository/chat.dart
  lib/domain/service/chat.dart
  lib/provider/gql/components/chat.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/event/chat.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  schema.graphql
  test/unit/chat_avatar_test.dart
  test/unit/chat_edit_message_test.dart
  test/widget/chat_edit_message_test.dart
Labels: enhancement, k::refactor

#637 Fix favorite `Chat`s and `Contact`s sorting (#606)
  lib/domain/model/chat.dart
  lib/store/chat.dart
  lib/store/contact.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/view.dart
  test/e2e/steps/see_favorite_monolog.dart
Labels: enhancement, k::UI/UX, k::refactor

#631 Add extension for Credentials to API (#629)
  lib/api/backend/extension/credentials.dart
  lib/store/auth.dart
  lib/ui/worker/background/src/main.dart
  test/e2e/configuration.dart
  test/e2e/world/custom_world.dart
Labels: enhancement, k::refactor

#648 `ChatForwardView` pagination (#216)
  lib/domain/model/user.dart
  lib/store/chat.dart
  lib/store/contact.dart
  lib/store/pagination.dart
  lib/store/pagination/combined_pagination.dart
  lib/store/pagination/graphql.dart
  lib/store/search.dart
  lib/store/user.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#628 Use ImageFile width and height in MediaAttachments(#525)
  CHANGELOG.md
  lib/domain/model/attachment.dart
  lib/domain/model/native_file.dart
  lib/store/chat.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/worker/cache.dart
Labels: enhancement, k::UI/UX

#657 `MessageFieldMore` appearance animation (#641)
  CHANGELOG.md
  lib/ui/page/call/controller.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/home/page/chat/message_field/component/more.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/widget/context_menu/mobile.dart
Labels: enhancement, k::UI/UX, k::refactor

#656 Fix `media_kit` crashing on macOS
  .github/workflows/ci.yml
  CHANGELOG.md
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/store/my_user.dart
  lib/themes.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/contact_tile.dart
  lib/ui/page/home/widget/safe_scrollbar.dart
  lib/ui/page/work/page/freelance/widget/issue.dart
  lib/ui/widget/menu_button.dart
Labels: enhancement, k::UI/UX, platform::macos

#644 Subscribe for visible chats (#607)
  lib/domain/repository/chat.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
Labels: enhancement, k::refactor

#655 Fix chat events race
  lib/store/chat.dart
Labels: enhancement, k::UI/UX

#658 Bump up project version to 0.1.0-alpha.10.1
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#660 Rephrase explicit types Contribution Guide rule
  CONTRIBUTING.md
Labels: k::documentation, enhancement

#667 Upgrade to 0.1.0-beta.12 backend version
  schema.graphql
Labels: enhancement, k::refactor

#662 Redesign `index.html` loading animation (#634)
  CHANGELOG.md
  lib/ui/page/call/widget/participant/widget.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/widget/progress_indicator.dart
  test/e2e/features/chat/sending_status/messages.feature
  test/e2e/features/home/mute/.feature
  test/e2e/steps/wait_until_attachment_status.dart
  web/index.html
Labels: enhancement, k::UI/UX

#674 Redesign delete message modal (#580)
  lib/ui/page/call/widget/participant/widget.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/rectangle_button.dart
  lib/ui/widget/progress_indicator.dart
  pubspec.yaml
Labels: enhancement, k::UI/UX

#672 Fix save button behavior (#575)
  CHANGELOG.md
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::UI/UX, k::refactor

#679 Disable `textScaleFactor` (#411)
  CHANGELOG.md
  lib/main.dart
Labels: enhancement, k::UI/UX

#668 Redesign `Introduction` modal
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/provider/gql/components/user.dart
  lib/routes.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/my_profile/widget/copyable.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/num.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  lib/ui/page/style/view.dart
  lib/ui/page/work/page/backend/controller.dart
  lib/ui/page/work/page/backend/view.dart
  lib/ui/page/work/page/freelance/controller.dart
  lib/ui/page/work/page/freelance/view.dart
  lib/ui/page/work/page/frontend/controller.dart
  lib/ui/page/work/page/frontend/view.dart
  lib/ui/widget/text_field.dart
  test/e2e/features/home/introduction/.feature
  test/e2e/steps/text_field.dart
  web/icons/apple-icon-114x114.png
  web/icons/apple-icon-120x120.png
  web/icons/apple-icon-144x144.png
  web/icons/apple-icon-152x152.png
  web/icons/apple-icon-180x180.png
  web/icons/apple-icon-57x57.png
  web/icons/apple-icon-60x60.png
  web/icons/apple-icon-72x72.png
  web/icons/apple-icon-76x76.png
  web/icons/apple-icon-precomposed.png
  web/icons/apple-icon.png
Labels: enhancement, k::UI/UX, k::refactor
