Repository team113/messenger, pull requests merged in 2023-07, with the labels that each got.

#463 Chats and contacts tabs `more` menu
  CHANGELOG.md
  assets/icons/search_exit.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/search/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/hovered_ink.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/widget/selected_dot.dart
  test/e2e/features/home/chats/selection/.feature
  test/e2e/features/home/contacts/selection/.feature
  test/e2e/parameters/keys.dart
Labels: enhancement, k::UI/UX, k::refactor

#421 Fix duplicate `GlobalKey` occurs when switching chats (#355)
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/view.dart
  test/e2e/steps/wait_until_message_status.dart
Labels: enhancement, k::refactor

#469 Fix flaky media updating
  lib/api/backend/extension/chat.dart
  lib/api/backend/graphql/query/chat/GetAttachments.graphql
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/widget/retry_image.dart
Labels: enhancement, k::UI/UX, k::refactor

#458 Add `User-Agent` header to network queries
  .github/workflows/ci.yml
  Makefile
  assets/conf.toml
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  lib/config.dart
  lib/provider/gql/base.dart
  lib/provider/gql/websocket/interface.dart
  lib/provider/gql/websocket/io.dart
  lib/provider/gql/websocket/web.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/util/ios_utils.dart
  lib/util/platform_utils.dart
  lib/util/pubspec_builder.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/e2e/hook/reset_app.dart
  test/e2e/mock/graphql.dart
  test/e2e/steps/internet.dart
  test/widget/auth_test.dart
Labels: enhancement, feature, k::api, k::config, k::refactor, k::toolchain

#468 Video improvements (#452)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/widget/round_button.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/desktop_controls.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/page/chat/widget/mobile_controls.dart
  lib/ui/page/home/page/chat/widget/rewind_indicator.dart
  lib/ui/page/home/page/chat/widget/video.dart
  lib/ui/page/home/page/chat/widget/video_progress_bar.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/gallery_popup.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#428 Refactor `HomeView` Page `chat -> view.dart` `Widgets` functions to `Widget` classes
  lib/l10n/l10n.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_subtitle.dart
  lib/ui/page/home/page/chat/widget/time_label.dart
  lib/ui/page/home/page/chat/widget/unread_label.dart
  test/unit/datetime_relative_test.dart
Labels: enhancement, k::refactor

#472 Call notifications
  CHANGELOG.md
  assets/audio/reconnect.mp3
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/ongoing_call.dart
  lib/themes.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/notification.dart
  lib/ui/page/home/page/chat/widget/video_progress_bar.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/animated_typing.dart
Labels: enhancement, k::UI/UX, k::refactor

#470 Add animations on icons hovering and pressing
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/user.dart
  lib/provider/gql/exceptions.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/back_button.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/copyable.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/page/user/widget/name.dart
  lib/ui/page/home/page/user/widget/num.dart
  lib/ui/page/home/page/user/widget/status.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/widget/animated_button.dart
  lib/ui/page/home/widget/field_button.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/widget/animated_button.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/member_tile.dart
  lib/ui/widget/text_field.dart
  test/e2e/features/chat/monolog/.feature
  test/e2e/steps/text_field.dart
Labels: enhancement, k::UI/UX, k::refactor

#477 Remove meaningless logs from E2E CI stage
  .github/workflows/ci.yml
  lib/util/pubspec_builder.dart
Labels: enhancement, k::toolchain

#478 Update `HiveChatItem` storage key
  lib/domain/model/chat_item.dart
  lib/domain/model/precise_date_time/src/non_web.dart
  lib/domain/model/precise_date_time/src/web.dart
  lib/provider/hive/base.dart
  lib/provider/hive/chat_item.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/util/obs/obs.dart
  lib/util/obs/rxlist.dart
  test/unit/precise_date_time_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#461 Bump up project version to 0.1.0-alpha.9
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#487 Fix `ChatRepository.readUntil` spam
  CHANGELOG.md
  lib/api/backend/extension/chat.dart
  lib/domain/model/chat.dart
  lib/domain/service/notification.dart
  lib/store/chat_rx.dart
  lib/themes.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/page/my_profile/camera_switch/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/worker/call.dart
  lib/util/platform_utils.dart
  test/e2e/features/chat/draft/.feature
  test/e2e/steps/see_chat_avatar.dart
  test/e2e/steps/see_draft.dart
  test/unit/chat_read_test.dart
Labels: enhancement, k::refactor

#488 Bump up project version to 0.1.0-alpha.9.1
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#485 Display chat links with "`-`" correctly
  lib/domain/model/user.dart
  test/unit/direct_link_slug_test.dart
Labels: enhancement, k::refactor

#489 Replace `FixedDigitsExtension` with `FontFeature.tabularFigures` (#482)
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/tab/chats/widget/rectangular_call_button.dart
Labels: enhancement, k::refactor

#493 Pin `chromedriver` version to `114.0.5735.90` in `test E2E` CI job
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain

#491 Account `Locale` mismatches in `L10n.init`
  CHANGELOG.md
  lib/l10n/l10n.dart
  lib/ui/worker/background/src/main.dart
  lib/ui/worker/settings.dart
Labels: enhancement, k::refactor

#494 Implement `AudioUtils` (#490)
  lib/domain/service/notification.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/worker/call.dart
  lib/util/audio_utils.dart
  lib/util/media_utils.dart
Labels: enhancement, k::refactor

#495 Migrate from `wakelock` to `wakelock_plus`
  ios/Podfile.lock
  lib/ui/page/popup_call/controller.dart
  lib/ui/worker/call.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor

#496 Refactor `AudioUtils` to use `media_kit`
  .github/workflows/ci.yml
  lib/provider/gql/components/chat.dart
  lib/ui/page/home/page/chat/widget/chat_subtitle.dart
  lib/util/audio_utils.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::refactor

#498 Bump up project version to 0.1.0-alpha.9.2
  .github/workflows/ci.yml
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement
