Repository team113/messenger, pull requests merged in 2023-04, with the labels that each got.

#391 Сhat does not open if the draft contains a response to the message (#376)
  lib/domain/model/chat_item_quote.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#388 Implement links and emails detection in messages
  CHANGELOG.md
  android/app/src/main/AndroidManifest.xml
  lib/themes.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  test/unit/parse_links_test.dart
Labels: enhancement, feature, k::UI/UX, k::refactor

#393 Secondary panel scaling improvement
  CHANGELOG.md
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/participant.dart
  lib/ui/widget/context_menu/region.dart
Labels: enhancement, k::UI/UX, k::refactor

#378 Invoke `ReactiveTextField` validator with debounce (#372)
  lib/ui/widget/text_field.dart
  test/unit/text_field_state_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#404 Allow multiple running applications in Web (#368)
  lib/domain/model/ongoing_call.dart
  lib/domain/service/auth.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/home/router.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  web/index.html
Labels: enhancement, k::UI/UX, platform::web

#403 Alert favicon
  CHANGELOG.md
  lib/ui/worker/chat.dart
  lib/ui/worker/my_user.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  web/favicon.png
  web/icons/alert/android-icon-144x144.png
  web/icons/alert/android-icon-192x192.png
  web/icons/alert/android-icon-36x36.png
  web/icons/alert/android-icon-48x48.png
  web/icons/alert/android-icon-72x72.png
  web/icons/alert/android-icon-96x96.png
  web/icons/alert/apple-icon-114x114.png
  web/icons/alert/apple-icon-120x120.png
  web/icons/alert/apple-icon-144x144.png
  web/icons/alert/apple-icon-152x152.png
  web/icons/alert/apple-icon-180x180.png
  web/icons/alert/apple-icon-57x57.png
  web/icons/alert/apple-icon-60x60.png
  web/icons/alert/apple-icon-72x72.png
  web/icons/alert/apple-icon-76x76.png
  web/icons/alert/apple-icon-precomposed.png
  web/icons/alert/apple-icon.png
  web/icons/alert/favicon-16x16.png
  web/icons/alert/favicon-32x32.png
  web/icons/alert/favicon-96x96.png
  web/icons/alert/favicon.ico
  web/icons/alert/ms-icon-144x144.png
  web/icons/alert/ms-icon-150x150.png
  web/icons/alert/ms-icon-310x310.png
  web/icons/alert/ms-icon-70x70.png
  web/icons/android-icon-144x144.png
  web/icons/android-icon-192x192.png
  web/icons/android-icon-36x36.png
  web/icons/android-icon-48x48.png
  web/icons/android-icon-72x72.png
  web/icons/android-icon-96x96.png
  web/icons/apple-icon-114x114.png
  web/icons/apple-icon-120x120.png
  web/icons/apple-icon-144x144.png
  web/icons/apple-icon-152x152.png
  web/icons/apple-icon-180x180.png
  web/icons/apple-icon-57x57.png
  web/icons/apple-icon-60x60.png
  web/icons/apple-icon-72x72.png
  web/icons/apple-icon-76x76.png
  web/icons/apple-icon-precomposed.png
  web/icons/apple-icon.png
  web/icons/favicon-16x16.png
  web/icons/favicon-32x32.png
  web/icons/favicon-96x96.png
  web/icons/favicon.ico
  web/icons/ms-icon-144x144.png
  web/icons/ms-icon-150x150.png
  web/icons/ms-icon-310x310.png
  web/icons/ms-icon-70x70.png
  web/index.html
Labels: enhancement, k::UI/UX, platform::web

#407 Reorder after dough break (#395)
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/widget/animated_transition.dart
  lib/ui/page/call/widget/reorderable_fit.dart
Labels: enhancement, k::UI/UX, k::refactor

#405 Change the color of the selected tiles
  CHANGELOG.md
  assets/icons/file_dark.svg
  assets/icons/muted_light.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/chat.dart
  lib/domain/repository/contact.dart
  lib/domain/service/chat.dart
  lib/domain/service/contact.dart
  lib/store/chat.dart
  lib/store/contact.dart
  lib/themes.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/my_profile/call_window_switch/view.dart
  lib/ui/page/home/page/my_profile/language/view.dart
  lib/ui/page/home/page/my_profile/timeline_switch/view.dart
  lib/ui/page/home/page/my_profile/widget/field_button.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/hovered_ink.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/chats/widget/search_user_tile.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/widget/animated_typing.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/home/widget/contact_tile.dart
  lib/ui/page/home/widget/rectangle_button.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/floating_snack_bar.dart
  lib/ui/widget/selected_dot.dart
Labels: enhancement, k::UI/UX, k::refactor
