Repository team113/messenger, pull requests merged in 2024-06, with the labels that each got.

#1018 Migrate `BlocklistRecord`s and `Background` persistence from Hive to `drift`
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/api/backend/extension/my_user.dart
  lib/api/backend/graphql/parsers/user.dart
  lib/domain/model/user.dart
  lib/domain/model_type_id.dart
  lib/main.dart
  lib/provider/drift/background.dart
  lib/provider/drift/blocklist.dart
  lib/provider/drift/drift.dart
  lib/provider/hive/background.dart
  lib/provider/hive/blocklist.dart
  lib/provider/hive/blocklist_sorting.dart
  lib/routes.dart
  lib/store/blocklist.dart
  lib/store/chat_rx.dart
  lib/store/model/background.dart
  lib/store/model/blocklist.dart
  lib/store/my_user.dart
  lib/store/settings.dart
  lib/ui/page/home/page/user/controller.dart
  pubspec.lock
  pubspec.yaml
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1019 Migrate `CacheInfo` persistence from Hive to `drift`
  assets/l10n/en-US.ftl
  lib/domain/model/cache_info.dart
  lib/domain/model/ongoing_call.dart
  lib/main.dart
  lib/provider/drift/cache.dart
  lib/provider/drift/drift.dart
  lib/provider/hive/cache.dart
  lib/store/my_user.dart
  lib/ui/worker/cache.dart
  test/e2e/features/home/chats/searching/.feature
  test/e2e/steps/scroll_until.dart
  test/unit/cache_worker_test.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, k::refactor

#1020 Migrate `ChatCallCredentials` persistence from Hive to `drift`
  lib/domain/repository/call.dart
  lib/provider/drift/call_credentials.dart
  lib/provider/drift/chat_credentials.dart
  lib/provider/drift/drift.dart
  lib/provider/hive/call_credentials.dart
  lib/provider/hive/chat_credentials.dart
  lib/routes.dart
  lib/store/call.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1022 Update l10n phrases related to email confirmation
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
Labels: enhancement, k::l10n

#1024 Migrate `Chat` drafts persistence from Hive to `drift`
  lib/domain/repository/chat.dart
  lib/provider/drift/call_credentials.dart
  lib/provider/drift/chat_credentials.dart
  lib/provider/drift/draft.dart
  lib/provider/drift/drift.dart
  lib/provider/hive/draft.dart
  lib/routes.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1025 Migrate `Chat` monologs persistence from Hive to `drift`
  lib/provider/drift/drift.dart
  lib/provider/drift/monolog.dart
  lib/provider/hive/monolog.dart
  lib/routes.dart
  lib/store/chat.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1026 Migrate `SessionData` persistence from Hive to `drift`
  lib/provider/drift/drift.dart
  lib/provider/drift/version.dart
  lib/provider/hive/session_data.dart
  lib/routes.dart
  lib/store/blocklist.dart
  lib/store/chat.dart
  lib/store/contact.dart
  lib/store/model/session_data.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/contact_rename_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1027 Migrate skipped `Release` version persistence from Hive to `drift` (#27)
  lib/main.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/skipped_version.dart
  lib/provider/drift/version.dart
  lib/provider/hive/skipped_version.dart
  lib/ui/worker/upgrade.dart
Labels: enhancement, k::refactor

#1028 Migrate `WindowPreferences` persistence from Hive to `drift` (#27)
  lib/main.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/window.dart
  lib/provider/hive/window.dart
  lib/ui/worker/window.dart
Labels: enhancement, k::refactor

#1030 Migrate `Credentials` persistence from Hive to `drift` (#27)
  lib/config.dart
  lib/domain/service/auth.dart
  lib/main.dart
  lib/provider/drift/account.dart
  lib/provider/drift/credentials.dart
  lib/provider/drift/drift.dart
  lib/provider/hive/account.dart
  lib/provider/hive/base.dart
  lib/provider/hive/credentials.dart
  lib/store/auth.dart
  lib/store/my_user.dart
  lib/store/pagination/hive.dart
  lib/store/pagination/hive_graphql.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/overlay/controller.dart
  lib/ui/page/home/overlay/view.dart
  test/e2e/hook/reset_app.dart
  test/e2e/steps/update_app_version.dart
  test/unit/auth_test.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/contact_rename_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/password_recovery_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1034 Prevent `media_kit` from copying `msvcp140.dll` to Windows build
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::dependencies

#1035 Bootstrap deep links configuration and resolving (#799)
  CHANGELOG.md
  android/app/src/main/AndroidManifest.xml
  assets/conf.toml
  ios/Podfile.lock
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/config.dart
  lib/main.dart
  lib/provider/drift/drift.dart
  lib/routes.dart
  lib/ui/page/home/page/my_profile/session/controller.dart
  lib/ui/page/home/page/my_profile/session/view.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  macos/Runner/AppDelegate.swift
  macos/Runner/Info.plist
  pubspec.lock
  pubspec.yaml
  web/.well-known/apple-app-site-association
  web/.well-known/assetlinks.json
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
  windows/runner/main.cpp
Labels: enhancement, feature, k::refactor

#1037 Remove l10n phrases of password recovery email
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
Labels: enhancement, k::l10n

#1001 Migrate `WebUtils` from `dart:html` to `package:web`
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/domain/model/precise_date_time/precise_date_time.dart
  lib/domain/service/notification.dart
  lib/provider/drift/settings.dart
  lib/provider/gql/base.dart
  lib/store/auth.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/page/chat/widget/web_image/web_image.dart
  lib/ui/widget/menu_interceptor/menu_interceptor.dart
  lib/ui/widget/menu_interceptor/src/web.dart
  lib/ui/widget/svg/src/web.dart
  lib/ui/widget/svg/svg.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  lib/util/web/web_utils.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor, platform::web

#1039 Fix `AudioUtils.once` pausing background music in iOS Safari (#968)
  CHANGELOG.md
  lib/util/audio_utils.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::UI/UX, k::refactor

#1040 Cover accounts switching with E2E tests
  lib/ui/page/auth/view.dart
  lib/ui/page/home/tab/menu/accounts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  test/e2e/configuration.dart
  test/e2e/features/auth/switch_account/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/accounts.dart
  test/e2e/steps/name_is.dart
  test/e2e/steps/users.dart
Labels: enhancement, k::testing

#1042 Gallery pagination (#216)
  lib/domain/repository/chat.dart
  lib/provider/drift/chat_item.dart
  lib/provider/drift/drift.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/paginated.dart
  lib/store/pagination.dart
  lib/store/pagination/drift.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_gallery.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
  test/e2e/configuration.dart
  test/e2e/features/pagination/gallery/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/posts_images.dart
  test/e2e/steps/tap_image.dart
  test/e2e/steps/tap_widget_n_times.dart
Labels: enhancement, k::UI/UX, k::refactor

#1044 Add missing entitlements to macOS application built on CI (#1043)
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain

#1041 Implement `conf.toml` Helm generation on-the-fly based on the domain (#954)
  helm/messenger/CHANGELOG.md
  helm/messenger/conf/nginx.conf
  helm/messenger/templates/configmap.yaml
  helm/messenger/templates/deployment.yaml
  lib/config.dart
  lib/ui/page/home/page/chat/controller.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, feature, k::deploy

#1051 Codesign iOS application (#1009)
  .github/workflows/ci.yml
  Makefile
  test/e2e/steps/appcast.dart
Labels: enhancement, k::toolchain

#1052 Use `git rev-list HEAD --count` for `--build-number` in `flutter.build` Makefile command
  Makefile
  lib/util/pubspec_builder.dart
  test/unit/version_test.dart
Labels: enhancement, k::refactor, k::toolchain

#1053 Bump up project version to 0.1.0
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement
