Repository team113/messenger, pull requests merged in 2024-08, with the labels that each got.

#1073 Fix `Query.chatItem` being sent when no `Chat`s persisted in `drift`
  lib/api/backend/extension/chat.dart
  lib/domain/model/chat.dart
  lib/provider/drift/chat_item.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/util/awaitable_timer.dart
Labels: enhancement, k::refactor

#1075 Replace `docker-compose` with `docker compose` in Makefile
  Makefile
Labels: enhancement, k::toolchain

#1076 Use forked `artemis` instead of discontinued one (#723)
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::dependencies

#995 Fix infinite typing when in the background on `mobile` platforms
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
Labels: enhancement, k::refactor

#1077 Force `AccountDriftProvider.read()` to always read from `drift` instead of relying on cache (#987)
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/provider/drift/account.dart
  lib/store/my_user.dart
  lib/ui/page/auth/controller.dart
  test/unit/chat_hide_test.dart
  test/widget/chat_hide_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1078 Close `GalleryPopup` whenever `RouterState.routes` change (#900)
  CHANGELOG.md
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/widget/context_menu/region.dart
Labels: enhancement, k::UI/UX, k::refactor

#1081 Upgrade Flutter to 3.24 version
  .github/workflows/ci.yml
  android/build.gradle
  dartdoc_options.yaml
  lib/routes.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/work/router.dart
  macos/Runner/AppDelegate.swift
  pubspec.lock
  pubspec.yaml
  test/e2e/features/chat/copying/.feature
  test/e2e/features/chat/selecting/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/tap_message.dart
  test_driver/integration_test_driver.dart
Labels: enhancement, k::refactor, k::dependencies

#1087 Implement signing up by `UserLogin` and `UserPassword`
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/auth.dart
  lib/domain/service/auth.dart
  lib/provider/gql/components/auth.dart
  lib/provider/gql/exceptions.dart
  lib/store/auth.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  test/e2e/configuration.dart
  test/e2e/features/auth/create_account/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/text_field.dart
  test/e2e/world/custom_world.dart
Labels: enhancement, k::UI/UX, k::refactor

#1089 Implement sign in and sign up by one-time password (#555)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/auth.dart
  lib/domain/service/auth.dart
  lib/domain/service/my_user.dart
  lib/provider/gql/components/auth.dart
  lib/store/auth.dart
  lib/ui/page/erase/controller.dart
  lib/ui/page/home/tab/menu/accounts/controller.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  lib/ui/page/login/widget/prefix_button.dart
  lib/ui/page/login/widget/sign_button.dart
  test/e2e/configuration.dart
  test/e2e/steps/users.dart
  test/e2e/world/custom_world.dart
  test/unit/auth_test.dart
  test/widget/auth_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1091 Confirm `UserEmail` deletion in a `DeleteUserEmail` modal
  .github/workflows/ci.yml
  lib/ui/page/home/page/my_profile/delete_email/controller.dart
  lib/ui/page/home/page/my_profile/delete_email/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  test/e2e/features/profile/emails/.feature
Labels: enhancement, k::UI/UX, k::refactor

#1094 Display country and city from `IpAddress` on `MyProfile` page (#1005)
  CHANGELOG.md
  assets/conf.toml
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/config.dart
  lib/domain/model/session.dart
  lib/domain/repository/my_user.dart
  lib/domain/repository/session.dart
  lib/domain/service/my_user.dart
  lib/domain/service/notification.dart
  lib/domain/service/session.dart
  lib/main.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/geolocation.dart
  lib/provider/geo/geo.dart
  lib/routes.dart
  lib/store/model/geo.dart
  lib/store/my_user.dart
  lib/store/session.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  test/e2e/configuration.dart
  test/e2e/mock/geo.dart
  test/e2e/steps/restart_app.dart
  test/mock/geo_provider.dart
  test/unit/chat_direct_link_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, feature, k::UI/UX, k::refactor

#1097 Replace `UserId.dialog` with `ChatService.monolog` within `ChatItemWidget` (#1083)
  CHANGELOG.md
  lib/store/chat.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
Labels: enhancement, k::UI/UX, k::refactor
