Repository team113/messenger, pull requests merged in 2024-04, with the labels that each got.

#932 Fix `Dock.onReorder()` callback not including added `CallButton`s
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/widget/dock.dart
Labels: enhancement, k::UI/UX, k::refactor

#927 Flaky local to remote `Chat` transition E2E test (#922)
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/pagination.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/util/obs/sorted_map.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, k::refactor

#934 Display `ImageFilter.blur`ed images in narrow `MediaAttachment`s
  CHANGELOG.md
  lib/provider/hive/application_settings.dart
  lib/provider/hive/background.dart
  lib/provider/hive/blocklist.dart
  lib/provider/hive/blocklist_sorting.dart
  lib/provider/hive/call_credentials.dart
  lib/provider/hive/call_rect.dart
  lib/provider/hive/chat.dart
  lib/provider/hive/chat_credentials.dart
  lib/provider/hive/chat_item.dart
  lib/provider/hive/chat_item_sorting.dart
  lib/provider/hive/chat_member.dart
  lib/provider/hive/chat_member_sorting.dart
  lib/provider/hive/contact.dart
  lib/provider/hive/contact_sorting.dart
  lib/provider/hive/credentials.dart
  lib/provider/hive/download.dart
  lib/provider/hive/draft.dart
  lib/provider/hive/favorite_chat.dart
  lib/provider/hive/favorite_contact.dart
  lib/provider/hive/media_settings.dart
  lib/provider/hive/monolog.dart
  lib/provider/hive/my_user.dart
  lib/provider/hive/recent_chat.dart
  lib/provider/hive/session_data.dart
  lib/provider/hive/skipped_version.dart
  lib/provider/hive/user.dart
  lib/provider/hive/window.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/widget/retry_image.dart
Labels: enhancement, k::UI/UX, k::refactor

#925 Bootstrap Sentry metrics
  .github/workflows/ci.yml
  ios/Podfile.lock
  lib/domain/service/notification.dart
  lib/main.dart
  lib/provider/gql/base.dart
  lib/provider/gql/components/auth.dart
  lib/provider/gql/components/call.dart
  lib/provider/gql/components/chat.dart
  lib/provider/gql/components/user.dart
  lib/ui/page/auth/controller.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/chat_direct_link/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/view.dart
  lib/ui/page/style/controller.dart
  lib/ui/page/work/controller.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/e2e/mock/graphql.dart
Labels: enhancement, k::monitoring, k::refactor, k::toolchain

#931 Bootstrap performance reporting in E2E tests
  test/e2e/configuration.dart
  test/e2e/features/user/blocklist/.feature
  test/e2e/hook/performance.dart
  test/e2e/hook/reset_app.dart
  test/e2e/steps/scroll_until.dart
  test/e2e/steps/see_search_results.dart
  test_driver/integration_test_driver.dart
Labels: enhancement, k::refactor, k::testing

#938 Fix `git describe` returning `-dirty` tags in `build` CI job
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain

#937 Fix sound when empty area pressed
  CHANGELOG.md
  lib/ui/widget/custom_page.dart
Labels: enhancement, k::refactor

#935 Play a sound when `CallMember` connects to `Call` (#928)
  CHANGELOG.md
  assets/audio/connected.mp3
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/widget/more_button.dart
  lib/ui/page/home/page/my_profile/call_buttons_switch/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/style/view.dart
  lib/ui/widget/context_menu/tile.dart
Labels: enhancement, k::UI/UX

#946 Bump up project version to 0.1.0-alpha.13
  .github/workflows/ci.yml
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement, k::toolchain

#942 Redesign `CustomAppBar`s of tabs and pages (#939)
  CHANGELOG.md
  assets/icons/work_flutter.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/l10n/l10n.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/tab/work/view.dart
  lib/ui/page/home/widget/app_bar.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/widget/menu_button.dart
Labels: enhancement, k::UI/UX, k::refactor

#908 Display `grab` cursor only over `RtcVideoView`s (#822)
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/participant/widget.dart
  lib/ui/page/call/widget/video_view.dart
Labels: enhancement, k::UI/UX, k::refactor

#951 Add `--windows-app-id` to `fcm.conf` Makefile command
  Makefile
Labels: enhancement, k::toolchain

#953 Bump up project version to 0.1.0-alpha.13.1
  CHANGELOG.md
  assets/conf.toml
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  helm/messenger/Chart.yaml
  lib/config.dart
  lib/domain/service/auth.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/work/page/backend/controller.dart
  lib/ui/page/work/page/backend/view.dart
  lib/ui/page/work/page/designer/controller.dart
  lib/ui/page/work/page/designer/view.dart
  lib/ui/page/work/page/freelance/controller.dart
  lib/ui/page/work/page/freelance/view.dart
  lib/ui/page/work/page/frontend/controller.dart
  lib/ui/page/work/page/frontend/view.dart
  lib/ui/page/work/widget/source_block.dart
  lib/ui/page/work/widget/vacancy_button.dart
  pubspec.yaml
Labels: k::documentation, enhancement, feature, k::UI/UX, k::config, k::refactor

#945 Implement global timer for synchronized periodic `UI` updates (#920)
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/animated_dots.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/chat_subtitle.dart
  lib/ui/page/home/tab/chats/widget/periodic_builder.dart
  lib/util/fixed_timer.dart
  test/unit/fixed_timer_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#944 Fix `Call` duration displaying incorrectly in `ChatCall` message
  CHANGELOG.md
  lib/store/chat_rx.dart
Labels: enhancement, k::UI/UX, k::refactor

#923 Events race on frequently sending requests (#444)
  lib/domain/model/crop_area.dart
  lib/domain/model/mute_duration.dart
  lib/domain/model/my_user.dart
  lib/domain/model/user.dart
  lib/store/event/my_user.dart
  lib/store/my_user.dart
  lib/ui/page/call/widget/dock.dart
  lib/util/event_pool.dart
  test/unit/event_pool_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_user_muting_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#955 Bump up project version to 0.1.0-alpha.13.2
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#962 Multiple `updateUserPassword` queries being sent when changing or setting password (#949)
  lib/domain/service/my_user.dart
  lib/ui/page/home/page/my_profile/password/controller.dart
Labels: enhancement, k::refactor

#963 Blurred buttons when creating group on `Chats` tab (#947)
  lib/ui/page/home/widget/shadowed_rounded_button.dart
Labels: enhancement, k::UI/UX, k::refactor

#940 Implement multiple `MyUser` and `Credentials` storage in `Hive`
  lib/api/backend/extension/my_user.dart
  lib/api/backend/extension/user.dart
  lib/api/backend/graphql/fragments/MyUser.graphql
  lib/api/backend/graphql/fragments/MyUserEventsVersioned.graphql
  lib/domain/model/my_user.dart
  lib/domain/model/session.dart
  lib/domain/repository/auth.dart
  lib/domain/repository/my_user.dart
  lib/domain/service/auth.dart
  lib/domain/service/my_user.dart
  lib/main.dart
  lib/provider/hive/account.dart
  lib/provider/hive/base.dart
  lib/provider/hive/chat.dart
  lib/provider/hive/credentials.dart
  lib/provider/hive/draft.dart
  lib/provider/hive/my_user.dart
  lib/routes.dart
  lib/store/auth.dart
  lib/store/event/my_user.dart
  lib/store/my_user.dart
  lib/ui/page/home/overlay/controller.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/popup_call/controller.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
  lib/ui/worker/background/background.dart
  lib/ui/worker/background/src/main.dart
  test/unit/auth_test.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/password_recovery_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#967 `AvatarWidget` not displaying `User.avatar` in `RecentChatTile` widget (#964)
  CHANGELOG.md
  lib/store/chat_rx.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/util/obs/sorted_map.dart
Labels: enhancement, k::UI/UX

#969 Bump up project version to 0.1.0-alpha.13.3
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#961 Prepare application for Google Play
  .github/workflows/ci.yml
  CHANGELOG.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/raw/ringtone.mp3
  assets/icons/menu_legal.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  assets/privacy.html
  assets/terms.html
  helm/messenger/conf/nginx.conf
  ios/Podfile.lock
  lib/config.dart
  lib/domain/service/notification.dart
  lib/l10n/l10n.dart
  lib/main.dart
  lib/routes.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/erase/controller.dart
  lib/ui/page/erase/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/tab/work/view.dart
  lib/ui/page/login/privacy_policy/view.dart
  lib/ui/page/login/terms_of_use/view.dart
  lib/ui/page/login/view.dart
  lib/ui/page/work/page/freelance/widget/issue.dart
  lib/ui/page/work/widget/project_block.dart
  lib/ui/widget/markdown.dart
  lib/ui/widget/menu_button.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/widget/upgrade_popup/view.dart
  lib/ui/worker/background/background.dart
  lib/ui/worker/background/src/main.dart
  lib/ui/worker/call.dart
  lib/util/get.dart
  lib/util/message_popup.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/features/auth/create_account/.feature
  test/e2e/features/chat/transition/.feature
  test/e2e/features/home/logout/.feature
  test/e2e/features/pagination/blocklist/.feature
  test/e2e/features/pagination/chat_members/.feature
  test/e2e/features/pagination/chats/.feature
  test/e2e/features/pagination/contacts/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/scroll_until.dart
  test/widget/auth_test.dart
Labels: k::documentation, enhancement, k::UI/UX, k::deploy, k::refactor

#970 Move `Contacts` tab button to `AppBar` of `Chats` tab
  CHANGELOG.md
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/view.dart
  lib/ui/widget/svg/svgs.dart
Labels: enhancement, k::UI/UX, k::refactor

#971 Bump up project version to 0.1.0-alpha.13.4
  CHANGELOG.md
  assets/conf.toml
  assets/icons/menu_help.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  helm/messenger/Chart.yaml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/config.dart
  lib/l10n/l10n.dart
  lib/routes.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/tab/work/view.dart
  lib/ui/page/login/view.dart
  lib/ui/page/support/view.dart
  lib/ui/page/work/page/designer/controller.dart
  lib/ui/page/work/page/designer/view.dart
  lib/ui/page/work/page/vacancy/view.dart
  lib/ui/page/work/widget/vacancy_button.dart
  lib/ui/widget/menu_button.dart
  lib/ui/widget/outlined_rounded_button.dart
  lib/ui/widget/svg/svgs.dart
  pubspec.lock
  pubspec.yaml
Labels: k::documentation, enhancement, k::UI/UX, k::refactor

#929 Implement Appcast track for releases (#896)
  .github/workflows/ci.yml
  .gitignore
  Makefile
  lib/domain/model/ongoing_call.dart
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: enhancement, k::deploy, k::toolchain

#982 Fix `appcast.xml` Makefile command omitting double quotes
  Makefile
Labels: enhancement, k::toolchain

#957 Don't allow invoking `AuthService.register` multiple times from `AuthView` (#770)
  lib/domain/service/auth.dart
  lib/domain/service/my_user.dart
  lib/provider/gql/components/auth.dart
  lib/provider/gql/components/user.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/password/view.dart
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  test/unit/auth_test.dart
  test/widget/password_recovery_test.dart
Labels: enhancement, k::refactor

#978 Fix user avatar double questions mark issue (#950)
  CHANGELOG.md
  lib/api/backend/graphql/mutation/user/SignIn.graphql
  lib/api/backend/graphql/mutation/user/SignUp.graphql
  lib/domain/model/session.dart
  lib/store/auth.dart
Labels: enhancement, k::refactor

#983 Fix Chat stack of images opening in focus mode (#979)
  CHANGELOG.md
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
Labels: enhancement, k::UI/UX, k::refactor
