Repository team113/messenger, pull requests merged in 2024-03, with the labels that each got.

#880 `GalleryPopup` in web has no `thumbhash` (#833)
  CHANGELOG.md
  lib/ui/page/home/page/chat/widget/web_image/src/non_web.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/page/home/widget/gallery_popup.dart
Labels: enhancement, k::UI/UX, k::refactor, platform::web

#875 Redesign `ContextMenu` over `CustomNavigationBar` (#838)
  assets/icons/pin_disabled.svg
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/page/style/page/icons/view.dart
  lib/ui/widget/context_menu/tile.dart
  lib/ui/widget/svg/svgs.dart
Labels: enhancement, k::UI/UX, k::refactor

#883 Set `PUB_CACHE` variable in `build` CI job on Windows temporary
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain, platform::windows

#864 Fix `Chat` not being removed from `Hive` when kicked (#851)
  CHANGELOG.md
  lib/domain/model/chat_call.dart
  lib/domain/model/chat_item.dart
  lib/domain/service/chat.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/chats/widget/search_user_tile.dart
  lib/ui/page/home/widget/contact_tile.dart
  lib/ui/widget/member_tile.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/members/.feature
  test/e2e/steps/remove_chat_member.dart
Labels: enhancement, k::UI/UX, k::refactor

#859 Fix new `ChatCallRoomJoinLink` completely resetting `RoomHandle` (#847)
  lib/domain/model/ongoing_call.dart
Labels: enhancement, k::refactor

#878 Refactor the way `RxUser` is checked against being in `Contact`s (#742)
  lib/api/backend/extension/user.dart
  lib/api/backend/graphql/fragments/User.graphql
  lib/domain/model/user.dart
  lib/domain/repository/contact.dart
  lib/domain/repository/user.dart
  lib/domain/service/auth.dart
  lib/routes.dart
  lib/store/contact.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/style/page/widgets/common/dummy_user.dart
  test/unit/call_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/pagination_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#877 Play a sound when leaving or left alone in a `Call` (#809)
  CHANGELOG.md
  assets/audio/end_call.wav
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/controller.dart
  lib/ui/worker/call.dart
Labels: enhancement, k::UI/UX, k::refactor

#881 Unnecessary `GraphQlProvider.chatItem()` queries when initializing `RxChat` (#879)
  lib/domain/repository/chat.dart
  lib/domain/repository/paginated.dart
  lib/provider/hive/chat_item.dart
  lib/provider/hive/chat_item_sorting.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/paginated.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, k::refactor

#886 Add `SafeArea`s to `MyProfileView` and `CallView` (#821)
  CHANGELOG.md
  android/app/src/main/res/values/styles.xml
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/widget/floating_fit/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#887 Add freelance section to README
  README.md
Labels: k::documentation, enhancement

#891 Redesign `MyProfile` page to display `UserBioField` in a separate `Block`
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/bio.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/page/home/page/my_profile/widget/name.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/widget/text_field.dart
  test/e2e/features/auth/create_account/.feature
  test/e2e/features/profile/l10n/.feature
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#893 Add `Config.schema` cleaning `Hive` storage on changes
  lib/config.dart
  lib/main.dart
Labels: enhancement, k::refactor

#894 Don't clean `CredentialsHiveProvider` on `Config.schema` changes
  lib/config.dart
  lib/main.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  web/index.html
Labels: enhancement, k::refactor

#892 Keep `CallMember`s in dialed state when `ChatCallRoomJoinLink` is changed
  lib/domain/model/ongoing_call.dart
Labels: enhancement, k::refactor

#885 Bring optimism to `ChatRepository`s `addChatMember` and `removeChatMember` (#858)
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/provider/gql/exceptions.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/info/add_member/controller.dart
  lib/ui/page/home/page/chat/info/add_member/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  test/unit/chat_members_test.dart
Labels: enhancement, k::UI/UX

#901 Wide `ImageAttachment`s are displayed with vertical spaces (#888)
  CHANGELOG.md
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/widget/retry_image.dart
  test/e2e/features/pagination/chats/.feature
Labels: enhancement, k::UI/UX, k::refactor

#903 Account local `ChatId`s in `ChatRepository.favoriteChat`
  lib/store/chat.dart
Labels: enhancement, k::refactor

#902 Add `ScrollController`s disposing (#866)
  .github/workflows/ci.yml
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/screen_share/controller.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/widget/message_info/controller.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  lib/ui/page/home/page/my_profile/blocklist/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/language/controller.dart
  lib/ui/page/home/page/my_profile/password/controller.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/home/tab/menu/status/controller.dart
  lib/ui/page/home/tab/work/controller.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/work/controller.dart
Labels: enhancement, k::refactor

#905 `SearchUserTile` unselects when dialog starts (#867)
  lib/domain/model/user.dart
  lib/routes.dart
  lib/ui/widget/member_tile.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::refactor

#897 Don't invoke `readChat`, when a popup is open (#854)
  CHANGELOG.md
  lib/domain/service/notification.dart
  lib/main.dart
  lib/routes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/router.dart
  lib/ui/page/work/router.dart
Labels: enhancement, k::UI/UX

#910 Fix `UserNum` formatting in notifications (#909)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  lib/ui/page/home/widget/avatar.dart
  lib/ui/widget/member_tile.dart
  lib/ui/worker/chat.dart
Labels: enhancement, k::UI/UX, k::refactor

#906 Fix `RetryImage` displays `CustomProgressIndicator` incorrectly (#835)
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/retry_image.dart
Labels: enhancement, k::UI/UX, k::refactor

#911 Floating panel in `Call` gets moved when rapidly resized (#806)
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX

#915 Fix background audio stops on `AudioUtilsImpl.once` (#912)
  CHANGELOG.md
  lib/util/audio_utils.dart
Labels: enhancement, k::UI/UX

#904 Implement and use static `tryParse()` methods for scalars (#846)
  lib/domain/model/chat.dart
  lib/domain/model/contact.dart
  lib/domain/model/my_user.dart
  lib/domain/model/user.dart
  lib/store/my_user.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/chat_direct_link/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/password/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/bio.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/page/home/page/my_profile/widget/name.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/tab/menu/status/controller.dart
  lib/ui/page/home/tab/menu/status/view.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/login/controller.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::refactor

#917 Use `RtcVideoRenderer.canPlay` for `VideoView` being loaded indication
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/widget/video_view.dart
Labels: enhancement, k::refactor

#916 Transition to another chat on forward tap (#216)
  assets/l10n/ru-RU.ftl
  lib/domain/repository/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
Labels: enhancement, k::UI/UX, k::refactor

#918 Edit message in group with one user (#627)
  lib/domain/model/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
Labels: enhancement, k::UI/UX, k::refactor

#914 Show a local notification if there's no push in 5-10 seconds (#687)
  CHANGELOG.md
  lib/domain/service/notification.dart
  lib/ui/worker/call.dart
  lib/ui/worker/chat.dart
Labels: enhancement, k::refactor, platform::web

#921 `Dock` animation lags, when moving `CallButton`s fast enough (#783)
  lib/ui/page/call/widget/dock.dart
Labels: enhancement, k::UI/UX, k::refactor

#924 Fix `appcast.xml` Makefile command missing `title` and `enclosure` tags
  Makefile
  lib/ui/worker/upgrade.dart
Labels: enhancement, k::refactor, k::toolchain

#919 Update `ChatCall` message according to `Call` updates (#455)
  CHANGELOG.md
  lib/domain/repository/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
Labels: enhancement, k::UI/UX, k::refactor
