Repository team113/messenger, pull requests merged in 2024-05, with the labels that each got.

#980 Redesign editing mode on `ChatInfo`, `User` and `MyProfile` pages (#948)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/store/chat.dart
  lib/store/my_user.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/background_preview.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/home/widget/quick_button.dart
  test/e2e/features/chat/avatar/.feature
  test/e2e/features/chat/monolog/.feature
  test/e2e/parameters/keys.dart
  test/unit/chat_direct_link_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_rename_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#984 Fix `ReactiveTextField` can be submitted with incorrect value on mobile
  android/app/src/main/AndroidManifest.xml
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/call/search/controller.dart
  lib/ui/page/erase/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/password/controller.dart
  lib/ui/page/home/page/my_profile/widget/bio.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/page/home/page/my_profile/widget/name.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/login/controller.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::refactor

#990 Messages might stuck at last, not loading the rest, despite `Chat.lastItem` changed (#691)
  lib/store/chat_rx.dart
Labels: enhancement, k::refactor

#986 List all active `Session`s and devices on `MyProfile` page (#566)
  .github/workflows/ci.yml
  CHANGELOG.md
  android/app/build.gradle
  assets/icons/menu_devices.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/Podfile.lock
  lib/api/backend/extension/my_user.dart
  lib/api/backend/graphql/query/user/Sessions.graphql
  lib/domain/repository/auth.dart
  lib/domain/service/auth.dart
  lib/domain/service/my_user.dart
  lib/l10n/l10n.dart
  lib/provider/gql/components/auth.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/routes.dart
  lib/store/auth.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/screen_share/view.dart
  lib/ui/page/erase/controller.dart
  lib/ui/page/erase/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/password/view.dart
  lib/ui/page/home/page/my_profile/session/controller.dart
  lib/ui/page/home/page/my_profile/session/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/page/login/view.dart
  lib/ui/page/style/page/widgets/section/buttons.dart
  lib/ui/page/work/widget/proceed_block.dart
  lib/ui/widget/menu_button.dart
  lib/ui/widget/primary_button.dart
  lib/ui/widget/upgrade_popup/view.dart
  lib/util/message_popup.dart
  lib/util/web/non_web.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/e2e/configuration.dart
  test/e2e/features/profile/sessions/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/see_sessions.dart
  test/e2e/steps/users.dart
  test/unit/user_agent_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#975 Implement account switching `UI` (#312)
  CHANGELOG.md
  assets/icons/logout.svg
  assets/icons/logout_white.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/session.dart
  lib/domain/repository/auth.dart
  lib/domain/repository/my_user.dart
  lib/domain/service/auth.dart
  lib/domain/service/my_user.dart
  lib/provider/gql/base.dart
  lib/provider/gql/components/auth.dart
  lib/routes.dart
  lib/store/auth.dart
  lib/store/my_user.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/menu/accounts/controller.dart
  lib/ui/page/home/tab/menu/accounts/view.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/popup_call/controller.dart
  lib/ui/widget/svg/svgs.dart
  lib/util/log.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  test/e2e/steps/users.dart
Labels: enhancement, feature, k::UI/UX, k::refactor

#992 Display `AuthService.accounts` on `Auth` page
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/auth.dart
  lib/domain/service/auth.dart
  lib/routes.dart
  lib/store/auth.dart
  lib/ui/page/auth/controller.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/tab/menu/accounts/view.dart
  lib/ui/page/home/tab/menu/confirm/controller.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/tab/menu/controller.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  test/e2e/features/home/logout/.feature
  test/e2e/features/my_user/online_status/.feature
  test/e2e/parameters/keys.dart
Labels: enhancement, k::UI/UX, k::refactor

#973 Use `Version` to detect critical releases in `UpgradeWorker`
  CHANGELOG.md
  assets/conf.toml
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/.editorconfig
  ios/PrivacyInfo.xcprivacy
  ios/Runner.xcodeproj/project.pbxproj
  lib/config.dart
  lib/main.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/style/page/widgets/section/buttons.dart
  lib/ui/widget/download_button.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/upgrade_popup/view.dart
  lib/ui/worker/upgrade.dart
  lib/util/pubspec_builder.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/configuration.dart
  test/e2e/features/home/upgrade/.feature
  test/e2e/parameters/appcast_version.dart
  test/e2e/parameters/keys.dart
  test/e2e/steps/appcast.dart
  test/unit/version_test.dart
Labels: enhancement, feature, k::UI/UX, k::config, k::refactor

#997 Upgrade Flutter to 3.22 version
  .github/workflows/ci.yml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/themes.dart
  lib/ui/widget/custom_page.dart
  lib/util/web/non_web.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::refactor, k::dependencies

#1002 Set `Cross-Origin-Embedder-Policy` header to `credentialless`
  helm/messenger/CHANGELOG.md
  helm/messenger/conf/nginx.conf
Labels: enhancement, k::deploy, k::security

#1003 Bump up `messenger` Helm chart version to 0.1.3
  helm/messenger/CHANGELOG.md
  helm/messenger/Chart.yaml
Labels: k::documentation, enhancement

#1013 Migrate `ChatMember`s persistence from Hive to `drift`
  lib/api/backend/extension/chat.dart
  lib/config.dart
  lib/domain/model_type_id.dart
  lib/provider/drift/chat_member.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/user.dart
  lib/provider/hive/chat_member.dart
  lib/provider/hive/chat_member_sorting.dart
  lib/routes.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/model/chat_member.dart
  lib/store/pagination/drift.dart
  lib/store/user.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/link/controller.dart
  lib/ui/page/link/view.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1016 Migrate `MyUser`s to `drift`
  lib/api/backend/extension/my_user.dart
  lib/domain/model/mute_duration.dart
  lib/domain/model/my_user.dart
  lib/domain/model_type_id.dart
  lib/domain/repository/my_user.dart
  lib/main.dart
  lib/provider/drift/chat_item.dart
  lib/provider/drift/chat_member.dart
  lib/provider/drift/connection/ffi.dart
  lib/provider/drift/connection/interface.dart
  lib/provider/drift/connection/js.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/my_user.dart
  lib/provider/drift/user.dart
  lib/provider/gql/components/user.dart
  lib/provider/hive/my_user.dart
  lib/routes.dart
  lib/store/auth.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/model/my_user.dart
  lib/store/my_user.dart
  lib/store/pagination/drift.dart
  lib/store/pagination/drift_graphql.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/util/event_pool.dart
  lib/util/obs/obs.dart
  test/e2e/hook/reset_app.dart
  test/mock/graphql_provider.dart
  test/unit/auth_test.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/contact_rename_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/password_recovery_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1014 Migrate `Chat`s to `drift`
  lib/api/backend/extension/chat.dart
  lib/domain/model/chat.dart
  lib/domain/model/chat_call.dart
  lib/domain/model_type_id.dart
  lib/domain/service/chat.dart
  lib/main.dart
  lib/provider/drift/chat.dart
  lib/provider/drift/chat_item.dart
  lib/provider/drift/chat_member.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/user.dart
  lib/provider/hive/chat.dart
  lib/provider/hive/favorite_chat.dart
  lib/provider/hive/my_user.dart
  lib/provider/hive/recent_chat.dart
  lib/routes.dart
  lib/store/auth.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/event/chat.dart
  lib/store/model/chat.dart
  lib/store/model/my_user.dart
  lib/store/model/page_info.dart
  lib/store/my_user.dart
  lib/store/pagination/drift.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/util/backoff.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  test/e2e/steps/users.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/contact_rename_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/password_recovery_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1017 Migrate `ApplicationSettings` persistence from Hive to `drift`
  lib/main.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/settings.dart
  lib/provider/hive/application_settings.dart
  lib/provider/hive/media_settings.dart
  lib/routes.dart
  lib/store/settings.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor
