Repository team113/messenger, pull requests merged in 2024-12, with the labels that each got.

#1149 Fix pasting URL from Safari being considered as a `FileAttachment` in `MessageFieldController` (#1148)
  lib/ui/page/home/page/chat/message_field/controller.dart
Labels: enhancement, k::UI/UX, k::refactor

#1151 Don't await upserting to `drift` in `Chat`s `Pagination`
  lib/store/pagination/drift_graphql.dart
Labels: enhancement, k::UI/UX, k::refactor

#1152 Use `{mode: 'shared'}` for Web Locks API when reading data from `drift`
  lib/provider/drift/background.dart
  lib/provider/drift/blocklist.dart
  lib/provider/drift/call_credentials.dart
  lib/provider/drift/call_rect.dart
  lib/provider/drift/chat.dart
  lib/provider/drift/chat_credentials.dart
  lib/provider/drift/chat_item.dart
  lib/provider/drift/chat_member.dart
  lib/provider/drift/credentials.dart
  lib/provider/drift/download.dart
  lib/provider/drift/draft.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/my_user.dart
  lib/provider/drift/session.dart
  lib/provider/drift/settings.dart
  lib/provider/drift/skipped_version.dart
  lib/provider/drift/user.dart
  lib/provider/drift/version.dart
  lib/provider/drift/window.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::refactor

#1153 Display incoming call when receiving tags ending with `-call` on Android
  android/app/proguard-rules.pro
  lib/main.dart
  lib/provider/gql/components/chat.dart
  test/e2e/steps/sends_message.dart
Labels: enhancement, k::UI/UX, k::refactor, platform::android

#1155 Upgrade to 0.2.1 backend version
  .github/workflows/ci.yml
  build.yaml
  dev/backend.toml
  docker-compose.yml
  helm/messenger/conf/nginx.conf
  lib/api/backend/graphql/mutation/user/RegisterPushDevice.graphql
  lib/api/backend/graphql/mutation/user/UnregisterPushDevice.graphql
  lib/api/backend/graphql/mutation/user/UpdateUserPassword.graphql
  lib/api/backend/graphql/parsers/user.dart
  lib/config.dart
  lib/domain/model/push_token.dart
  lib/domain/repository/auth.dart
  lib/domain/service/auth.dart
  lib/domain/service/notification.dart
  lib/provider/drift/drift.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/store/auth.dart
  lib/store/model/session.dart
  lib/store/model/version.dart
  lib/ui/page/home/page/chat/info/controller.dart
  schema.graphql
  test/unit/my_profile_emails_test.dart
Labels: enhancement, k::refactor

#1156 Bump up project version to 0.3.0
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  helm/messenger/Chart.yaml
  ios/fastlane/metadata/en-US/release_notes.txt
  pubspec.yaml
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement
