Repository team113/messenger, pull requests merged in 2024-11, with the labels that each got.

#1136 Bump up project version to 0.2.2
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  ios/Podfile.lock
  ios/fastlane/metadata/en-US/release_notes.txt
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement

#1130 Avatar cropping (#530)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/store/my_user.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/crop_avatar/controller.dart
  lib/ui/page/home/page/my_profile/crop_avatar/view.dart
  lib/ui/page/home/page/my_profile/crop_avatar/widget/image_cropper/enums.dart
  lib/ui/page/home/page/my_profile/crop_avatar/widget/image_cropper/painter.dart
  lib/ui/page/home/page/my_profile/crop_avatar/widget/image_cropper/widget.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/home/widget/big_avatar.dart
Labels: enhancement, feature, k::UI/UX, k::refactor

#1138 Fix `RecentChatTile` displayed as selected in `Chats` selecting mode
  helm/messenger/Chart.yaml
  lib/store/chat.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  pubspec.yaml
  test/e2e/steps/see_chat_avatar.dart
Labels: enhancement, k::refactor

#1139 Use `CropAvatar` modal for `Chat.avatar` cropping on `ChatInfo` page
  CHANGELOG.md
  lib/domain/repository/chat.dart
  lib/domain/service/chat.dart
  lib/provider/gql/components/chat.dart
  lib/store/chat.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/crop_avatar/widget/image_cropper/widget.dart
  lib/util/backoff.dart
Labels: enhancement, k::UI/UX, k::refactor

#1141 Use `super_clipboard` to support images and files pasting to message field
  CHANGELOG.md
  ios/Podfile.lock
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, feature, k::UI/UX, k::refactor

#1140 Drag-n-drop Attachments (#594)
  CHANGELOG.md
  android/app/src/main/AndroidManifest.xml
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/custom_drop_target.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/widget/chat_tile.dart
  lib/util/data_reader.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, feature, k::UI/UX

#1143 Fix `ImageCropper` using previous coordinates when scaling and moving crop area
  CHANGELOG.md
  lib/config.dart
  lib/domain/service/notification.dart
  lib/ui/page/home/page/chat/widget/custom_drop_target.dart
  lib/ui/page/home/page/my_profile/crop_avatar/widget/image_cropper/widget.dart
  lib/util/platform_utils.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1144 Add missing `isHidden` to `Chat.copyWith()`
  lib/domain/model/chat.dart
Labels: enhancement, k::UI/UX, k::refactor

#1145 Fix `onDidRemovePage` popping already popped pages (#1084)
  lib/routes.dart
Labels: enhancement, k::UI/UX, k::refactor

#1146 Persist `DtoChat.lastReadItemCursor` when receiving `EventChatRead`s
  lib/store/chat.dart
  lib/store/chat_rx.dart
Labels: enhancement, k::UI/UX, k::refactor
