Repository team113/messenger, pull requests merged in 2024-09, with the labels that each got.

#1099 Upgrade to 0.1.1 backend version
  dev/backend.toml
  lib/api/backend/graphql/fragments/SessionEventsVersioned.graphql
  lib/store/chat_rx.dart
  lib/store/event/session.dart
  lib/store/session.dart
  schema.graphql
Labels: enhancement, k::refactor

#1101 Fix `tags` step forming invalid tags in `docker-push` CI job
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain

#1098 Use `CustomSafeArea` to always add bottom paddings to PWAs on iOS devices (#1015)
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  lib/ui/page/auth/view.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/video/widget/mobile_controls.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/welcome_field/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/page/home/widget/safe_scrollbar.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/safe_area/safe_area.dart
  lib/ui/widget/safe_area/src/io.dart
  lib/ui/widget/safe_area/src/web.dart
Labels: enhancement, k::UI/UX, k::refactor, platform::ios, platform::web

#1102 Upgrade `media_kit` and dependencies to latest versions
  ios/Podfile.lock
  lib/ui/worker/my_user.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor, k::dependencies

#1103 Fix inability to input `ChatName` on `Chats` tab in Firefox
  CHANGELOG.md
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/widget/menu_interceptor/src/non_web.dart
  lib/ui/widget/menu_interceptor/src/web.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#1105 Fix `ChatCallWidget` not rebuilding periodically active `ChatCall`'s duration
  CHANGELOG.md
  lib/ui/page/home/page/chat/widget/chat_item.dart
Labels: enhancement, k::UI/UX, k::refactor

#1106 Fix finished `ChatCall`s being rapidly displayed on `Chats` tab during synchronization
  lib/api/backend/graphql/fragments/ChatEventsVersioned.graphql
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/event/chat.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  test/unit/call_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1104 Validate `fastlane` binaries and metadata on CI (#1065)
  .github/workflows/ci.yml
  android/fastlane/Fastfile
  helm/messenger/Chart.yaml
  ios/fastlane/Fastfile
  pubspec.yaml
Labels: enhancement, feature, k::refactor, k::toolchain

#1109 Periodically run `UpgradeWorker.fetchUpdates()` to fetch updates (#896)
  lib/ui/widget/floating_snack_bar.dart
  lib/ui/worker/upgrade.dart
  lib/util/message_popup.dart
Labels: enhancement, k::UI/UX, k::refactor

#1108 Fix restore button clipping chats on mobile platforms (#758)
  CHANGELOG.md
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/welcome_field/controller.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/util/platform_utils.dart
  test/e2e/steps/scroll_until.dart
Labels: enhancement, k::UI/UX, k::refactor

#1110 Bump up project version to 0.2.1
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  ios/Podfile.lock
  ios/fastlane/metadata/en-US/release_notes.txt
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement, k::dependencies

#1111 Account `ChatMember.joinedAt` date when determining `RxChat.reads` (#379)
  lib/store/chat_rx.dart
Labels: enhancement, k::refactor

#1113 Fix `PopupCallController.call` late initialization error (#889)
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/popup_call/controller.dart
  lib/ui/page/popup_call/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#1112 Implement swipe to reply trackpad gesture in `ChatItemWidget` (#296)
  CHANGELOG.md
  helm/messenger/Chart.yaml
  lib/ui/page/call/widget/dock.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/util/platform_utils.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#1115 Properly format file attachment sizes (#603)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/l10n/l10n.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/widget/data_attachment.dart
  lib/ui/page/home/page/my_profile/welcome_field/view.dart
  test/unit/file_size_formatting_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1117 Refactor `WebUtils.cameraPermission()` to hold tracks active while `CameraSwitch` modal is opened
  CHANGELOG.md
  lib/ui/page/home/page/my_profile/camera_switch/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/controller.dart
  lib/ui/page/home/page/my_profile/output_switch/controller.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::UI/UX, k::refactor

#1120 Use `resizeUpLeftDownRight` and `resizeUpRightDownLeft` custom cursors in `Call` view on macOS (#568)
  CHANGELOG.md
  assets/images/resizeUpLeftDownRight.png
  assets/images/resizeUpRightDownLeft.png
  lib/ui/page/call/component/desktop.dart
  lib/util/platform_utils.dart
Labels: enhancement, k::UI/UX, k::refactor
