Repository team113/messenger, pull requests merged in 2024-01, with the labels that each got.

#745 Restore deleted/hidden notes chat (#582)
  CHANGELOG.md
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  test/e2e/configuration.dart
  test/e2e/features/home/chats/monolog/.feature
  test/e2e/parameters/credentials.dart
  test/e2e/steps/long_press_chat.dart
  test/e2e/steps/see_search_results.dart
  test/e2e/steps/set_login.dart
  test/e2e/steps/text_field.dart
  test/unit/chat_hide_test.dart
  test/widget/chat_hide_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#775 Improve the animation of the transition between chats (#573)
  CHANGELOG.md
  lib/themes.dart
  lib/ui/widget/custom_page.dart
Labels: enhancement, k::UI/UX, k::refactor

#791 Remove timeline mode from `Chat` (#788)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/application_settings.dart
  lib/store/settings.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/swipeable_status.dart
  lib/ui/page/home/page/chat/widget/time_label.dart
  lib/ui/page/home/page/my_profile/timeline_switch/controller.dart
  lib/ui/page/home/page/my_profile/timeline_switch/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/widget/menu_button.dart
Labels: enhancement, k::UI/UX, k::refactor

#786 Fade out `Attachment`s when dismissing by swipe (#699)
  CHANGELOG.md
  lib/ui/page/home/page/chat/message_field/view.dart
Labels: enhancement, k::UI/UX

#796 Redesign `DirectLinkField` widget on `MyProfile` and `ChatInfo` pages (#787)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/ongoing_call.dart
  lib/provider/hive/background.dart
  lib/routes.dart
  lib/store/settings.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/background_preview.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/work/widget/vacancy_button.dart
  lib/ui/widget/modal_popup.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#764 Don't display `Chat.ongoingCall`, while still fetching data from backend (#581)
  lib/store/chat.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
Labels: enhancement, k::refactor

#798 Implement and use `Config.link` for `ChatDirectLink`s
  .github/workflows/ci.yml
  assets/conf.toml
  lib/config.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/widget/direct_link.dart
Labels: enhancement, feature, k::config, k::refactor, k::toolchain

#794 Redesign `MyProfile` page (#789)
  CHANGELOG.md
  assets/icons/menu_nav.svg
  assets/icons/password_small.svg
  assets/icons/password_small_white.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/domain/model/cache_info.dart
  lib/domain/repository/settings.dart
  lib/provider/gql/exceptions.dart
  lib/provider/hive/application_settings.dart
  lib/provider/hive/cache.dart
  lib/routes.dart
  lib/store/settings.dart
  lib/themes.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/page/home/page/my_profile/widget/status.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/page/home/widget/field_button.dart
  lib/ui/page/home/widget/info_tile.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/page/style/page/widgets/section/navigation.dart
  lib/ui/widget/menu_button.dart
  lib/ui/widget/outlined_rounded_button.dart
  lib/ui/widget/selector.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/widget/text_field.dart
  lib/ui/worker/cache.dart
  pubspec.lock
  pubspec.yaml
  test/e2e/features/profile/emails/.feature
  test/e2e/features/profile/phones/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/text_field.dart
  test/unit/cache_worker_test.dart
  test/widget/auth_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#785 Fix re-`submit` not working when `password` hasn't been changed (#782)
  lib/ui/page/home/page/my_profile/password/controller.dart
  lib/ui/page/login/controller.dart
Labels: enhancement, k::UI/UX, k::refactor

#784 Fix `ChatEvents` may be ignored (#777)
  lib/provider/hive/base.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  test/widget/auth_test.dart
  test/widget/chat_hide_test.dart
Labels: enhancement, k::refactor

#797 Fix video `PopupCall`s starting without camera enabled
  CHANGELOG.md
  assets/icons/low_signal.svg
  assets/icons/low_signal_level.svg
  assets/icons/no_signal.svg
  lib/routes.dart
  lib/store/call.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/widget/participant/overlay.dart
  lib/ui/page/popup_call/controller.dart
  lib/ui/widget/svg/svgs.dart
Labels: enhancement, k::UI/UX, k::refactor

#771 `ContactRepository.createChatContact` events pre-handling (#767)
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
  lib/domain/service/contact.dart
  lib/store/contact.dart
  lib/ui/page/home/page/user/view.dart
  test/e2e/features/contact/adding/.feature
  test/e2e/parameters/keys.dart
  test/e2e/steps/see_favorite_contact.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#760 Use `WebUtils.mutex` for `renewSession` synchronization (#728)
  assets/conf.toml
  lib/config.dart
  lib/domain/model/ongoing_call.dart
  lib/domain/service/auth.dart
  lib/main.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/util/awaitable_timer.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/unit/auth_test.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_phones_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/password_recovery_test.dart
  test/widget/user_profile_test.dart
  web/index.html
Labels: enhancement, k::refactor, platform::web

#816 Grab cursor when dragging `Participant`s in `Call` (#810)
  CHANGELOG.md
  assets/images/grab.bgra
  assets/images/grabbing.bgra
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/widget/outlined_rounded_button.dart
  lib/util/platform_utils.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::UI/UX

#818 Fix Helm deployment not copying hidden files
  helm/messenger/CHANGELOG.md
  helm/messenger/Chart.yaml
  helm/messenger/templates/deployment.yaml
Labels: enhancement, k::deploy

#823 Use `all_sensors` for `proximityEvents` to dim the screen in `Call` (#808)
  .gitignore
  CHANGELOG.md
  lib/ui/page/call/controller.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, feature, k::UI/UX

#804 Fix animation in `ReactiveTextField`s `suffix` (#803)
  assets/icons/timer.svg
  lib/ui/page/home/page/my_profile/widget/status.dart
  lib/ui/page/login/controller.dart
  lib/ui/widget/animations.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/outlined_rounded_button.dart
  lib/ui/widget/text_field.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
Labels: enhancement, k::UI/UX, k::refactor
