Repository team113/messenger, pull requests merged in 2024-02, with the labels that each got.

#829 Remove `ApplicationSettings.loadImages` setting (#826)
  lib/domain/model/application_settings.dart
  lib/domain/repository/settings.dart
  lib/provider/hive/application_settings.dart
  lib/store/settings.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/media_attachment.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/widget/retry_image.dart
Labels: enhancement, k::api, k::refactor

#827 Allow `UserLoginField` to be editable on `MyProfile` page (#813)
  CHANGELOG.md
  assets/icons/edit_field.svg
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/login.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::UI/UX, k::refactor

#805 Redesign `SearchView` (#790)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  lib/domain/service/user.dart
  lib/store/chat_rx.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/search/widget/search_field.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/info/add_member/controller.dart
  lib/ui/page/home/page/chat/info/add_member/view.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/password/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/widget/field_button.dart
  lib/ui/page/home/widget/shadowed_rounded_button.dart
  lib/ui/page/login/view.dart
  lib/ui/page/login/widget/primary_button.dart
  lib/ui/page/style/page/widgets/section/buttons.dart
  lib/ui/page/work/widget/proceed_block.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/outlined_rounded_button.dart
  lib/ui/widget/selected_tile.dart
  lib/util/message_popup.dart
Labels: enhancement, k::UI/UX, k::refactor

#837 Add secondary panel modes switches to `Call` (#811)
  CHANGELOG.md
  assets/icons/call_floating.svg
  assets/icons/call_gallery.svg
  assets/icons/call_side.svg
  assets/icons/fullscreen_enter_small.svg
  assets/icons/fullscreen_exit_small.svg
  lib/domain/service/my_user.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/widget/title_bar.dart
  lib/ui/widget/svg/svgs.dart
Labels: enhancement, k::UI/UX, k::refactor

#815 Comment out `deploy-sentry` CI job
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  android/app/build.gradle
  lib/domain/service/auth.dart
  lib/main.dart
  lib/util/log.dart
  lib/util/pubspec_builder.dart
  lib/util/web/web.dart
Labels: enhancement, k::refactor, k::toolchain

#834 Bump up project version to 0.1.0-alpha.12
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#844 Bump up project version to 0.1.0-alpha.12.1
  CHANGELOG.md
  helm/messenger/Chart.yaml
  lib/util/web/web.dart
  pubspec.yaml
  web/index.html
Labels: k::documentation, enhancement, k::refactor

#832 Improve outgoing `Call`s UI/UX (#812)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/call.dart
  lib/domain/service/call.dart
  lib/store/call.dart
  lib/themes.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/component/mobile.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/call/widget/call_button.dart
  lib/ui/page/call/widget/call_cover.dart
  lib/ui/page/call/widget/call_title.dart
  lib/ui/page/call/widget/round_button.dart
  lib/ui/page/call/widget/video_view.dart
  lib/ui/page/home/widget/avatar.dart
  lib/ui/page/login/view.dart
  lib/ui/page/style/page/colors/view.dart
  lib/ui/page/style/page/widgets/section/call.dart
Labels: enhancement, k::UI/UX, k::refactor

#465 Dont switch manually selected media device(#464)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/call/widget/round_button.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/my_profile/camera_switch/controller.dart
  lib/ui/page/home/page/my_profile/camera_switch/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/controller.dart
  lib/ui/page/home/page/my_profile/microphone_switch/view.dart
  lib/ui/page/home/page/my_profile/output_switch/controller.dart
  lib/ui/page/home/page/my_profile/output_switch/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/field_button.dart
  lib/util/media_utils.dart
Labels: enhancement, k::UI/UX, k::refactor

#843 Improve search via `ChatDirectLink` algorithm (#831)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  lib/domain/model/user.dart
  lib/ui/page/call/search/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  test/e2e/configuration.dart
  test/e2e/features/home/chats/monolog/.feature
  test/e2e/features/home/chats/searching/.feature
  test/e2e/parameters/credentials.dart
  test/e2e/steps/see_search_results.dart
  test/e2e/steps/set_credential.dart
  test/e2e/steps/text_field.dart
Labels: enhancement, k::UI/UX, k::refactor

#848 Add `IntroductionViewStage.link` to `Introduction` modal (#820)
  CHANGELOG.md
  assets/icons/logo.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/l10n/l10n.dart
  lib/routes.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/chat_direct_link/controller.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/style/page/icons/view.dart
  lib/ui/page/work/widget/project_block.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/widget/svg/svgs.dart
  lib/util/web/web.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor

#855 Fix `TypeError` when accessing Permissions API in Firefox
  CHANGELOG.md
  lib/ui/worker/chat.dart
  lib/util/media_utils.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::UI/UX, k::refactor

#860 Upgrade Flutter to 3.19 version
  .github/workflows/ci.yml
  ios/Podfile.lock
  lib/main.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/widget/dock.dart
  lib/ui/page/call/widget/drop_box_area.dart
  lib/ui/page/call/widget/launchpad.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/worker/background/src/main.dart
  lib/ui/worker/cache.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::dependencies

#845 Implement `deploy-staging` CI job for deploying `edge` container
  .github/workflows/ci.yml
Labels: feature, k::deploy, k::toolchain

#861 Display `UserBio` in `ChatSubtitle` (#839)
  lib/store/event/user.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/widget/chat_subtitle.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/menu/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#856 Unsubscribe from `keepTyping`, when `MessageFieldView` loses its focus (#828)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/forward/view.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/widget/text_field.dart
Labels: enhancement, k::UI/UX, k::refactor

#863 Redesign `CustomNavigationBar` to use `ContextMenuTile`s
  CHANGELOG.md
  assets/icons/active_call_start_blue.svg
  assets/icons/muted22.svg
  assets/icons/unmuted22.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/auth/view.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/view.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/home/tab/work/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/navigation_bar.dart
  lib/ui/widget/context_menu/region.dart
  lib/ui/widget/context_menu/tile.dart
  lib/ui/widget/selector.dart
  lib/ui/widget/svg/svgs.dart
  macos/Podfile.lock
Labels: enhancement, k::UI/UX, k::refactor

#865 Bump up project version to 0.1.0-alpha.12.2
  .github/workflows/ci.yml
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement, k::toolchain

#869 Bump up project version to 0.1.0-alpha.12.3
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
Labels: k::documentation, enhancement

#868 Redesign `ChatInfo` and `User` pages
  CHANGELOG.md
  assets/icons/add_contact16.svg
  assets/icons/add_member_small.svg
  assets/icons/chat18.svg
  assets/icons/chat18_white.svg
  assets/icons/clean_history16.svg
  assets/icons/delete_contact16.svg
  assets/icons/edit_small.svg
  assets/icons/favorite16.svg
  assets/icons/muted16.svg
  assets/icons/report.svg
  assets/icons/report_white.svg
  assets/icons/share19.svg
  assets/icons/share19_white.svg
  assets/icons/unfavorite16.svg
  assets/icons/unmuted16.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/store/chat.dart
  lib/store/my_user.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/home/widget/quick_button.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/widget/text_field.dart
  macos/Podfile.lock
  test/e2e/features/chat/avatar/.feature
  test/e2e/features/chat/monolog/.feature
  test/e2e/parameters/keys.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_rename_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#824 Fix events not processed when version equals to stored
  lib/api/backend/graphql/query/chat/FavoriteChats.graphql
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/store/contact.dart
  lib/store/my_user.dart
  lib/store/user.dart
  lib/store/user_rx.dart
  lib/ui/page/home/tab/chats/view.dart
  test/e2e/configuration.dart
  test/e2e/features/chat/favorite/.feature
  test/e2e/steps/favorite_group.dart
  test/e2e/steps/users.dart
  test/e2e/world/custom_world.dart
  test/mock/graphql_provider.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor
