Repository team113/messenger, pull requests merged in 2025-06, with the labels that each got.

#1283 Remove unused `ChatButton`s
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/call.dart
  lib/ui/page/call/component/common.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/widget/buttons.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/widget/animated_typing.dart
  lib/ui/page/home/widget/big_avatar.dart
  lib/ui/page/home/widget/contact_tile.dart
Labels: enhancement, k::refactor

#1285 Fix `LoginController.recovery` not acknowledging data from `LoginController.login` field
  CHANGELOG.md
  lib/l10n/l10n.dart
  lib/ui/page/call/participant/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/accounts/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/login/view.dart
  lib/ui/page/style/page/typography/view.dart
  lib/ui/page/work/router.dart
  lib/ui/widget/text_field.dart
  test/e2e/configuration.dart
  test/e2e/features/auth/account_recovery/.feature
  test/e2e/mock/graphql.dart
  test/e2e/parameters/keys.dart
  test/e2e/steps/see_field_having_error.dart
Labels: enhancement, k::UI/UX, k::refactor

#1284 Handle `Call` related exceptions straight in `CallRepository` instead of throwing those
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/domain/repository/call.dart
  lib/domain/repository/settings.dart
  lib/domain/service/call.dart
  lib/provider/gql/exceptions.dart
  lib/store/call.dart
  lib/store/settings.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/search/view.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/call/widget/hint.dart
  lib/ui/page/erase/confirm_delete/view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/message_field/widget/chat_button.dart
  lib/ui/page/home/page/chat/widget/message_info/view.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/add_phone/controller.dart
  lib/ui/page/home/page/my_profile/add_phone/view.dart
  lib/ui/page/home/page/my_profile/call_buttons_switch/controller.dart
  lib/ui/page/home/page/my_profile/call_buttons_switch/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/delete_email/view.dart
  lib/ui/page/home/page/my_profile/link_details/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/bio.dart
  lib/ui/page/home/page/my_profile/widget/name.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/controller.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/accounts/view.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/view.dart
  lib/ui/page/style/page/widgets/section/fields.dart
Labels: enhancement, k::UI/UX, k::refactor

#1294 Update default order of `CallButton`s (#1263)
  CHANGELOG.md
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX, k::refactor

#1291 Redesign `ChatMessage` delete popup (#1268)
  CHANGELOG.md
  assets/icons/delete19_white.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/widget/confirm_dialog.dart
  lib/ui/widget/svg/svgs.dart
  lib/util/message_popup.dart
  test/e2e/features/chat/delete_messages/.feature
  test/e2e/parameters/keys.dart
Labels: enhancement, k::UI/UX, k::refactor

#1299 Clear `MyUser` related `ScopedDatabase` when `AuthService.logout()` is invoked
  lib/domain/service/auth.dart
  lib/domain/service/call.dart
  lib/provider/drift/drift.dart
  lib/routes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/util/log.dart
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Release.entitlements
Labels: enhancement, k::refactor

#1302 Fix scroll back button not scrolling `Chat` to its last item
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
Labels: enhancement, k::UI/UX, k::refactor

#1303 Add required `<script>` tag for `pwa_install` package to `index.html`
  CHANGELOG.md
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor, platform::web

#1305 Remove onDragging parameter (#1292)
  lib/ui/page/home/page/my_profile/view.dart
  test/unit/cache_worker_test.dart
Labels: enhancement, k::refactor
