Repository team113/messenger, pull requests merged in 2025-05, with the labels that each got.

#1230 Don't invoke `GraphQlProvider.refreshSession()` while application is inactive
  lib/domain/service/auth.dart
  lib/ui/page/home/page/chat/controller.dart
  test/unit/auth_test.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/password_recovery_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor

#1233 Remove `AppLifecycleState` worker from `AuthService`
  lib/domain/service/auth.dart
Labels: enhancement, k::refactor

#1237 Fix ghosts of `CallButton`s hanging when dragged fast enough (#1236)
  CHANGELOG.md
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
Labels: enhancement, k::UI/UX, k::refactor

#1229 Redesign `UpgradePopup` to display upgrade alert on `Auth` page
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/main.dart
  lib/ui/page/auth/controller.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/view.dart
  lib/ui/widget/upgrade_available_button.dart
  lib/ui/worker/upgrade.dart
  test/e2e/features/home/upgrade/.feature
  test/widget/auth_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1231 Bump up project version to 0.4.3
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement

#1238 Fix `GetAttachments` GraphQL query fetching originals instead of quotes for replies
  CHANGELOG.md
  helm/messenger/Chart.yaml
  lib/api/backend/extension/chat.dart
  lib/api/backend/graphql/query/chat/GetAttachments.graphql
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#1239 Upgrade to 0.5.0 backend version
  lib/domain/service/auth.dart
  lib/domain/service/notification.dart
  lib/routes.dart
  lib/ui/page/home/page/my_profile/welcome_field/view.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/page/home/widget/direct_link.dart
  schema.graphql
Labels: enhancement, k::refactor, k::dependencies

#1240 Bump up project version to 0.5.0
  CHANGELOG.md
  helm/messenger/Chart.yaml
  pubspec.yaml
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement

#1243 Use `FutureOrBuilder` for `RxUser` related `FutureOr` resolving
  CHANGELOG.md
  helm/messenger/Chart.yaml
  lib/provider/gql/base.dart
  lib/provider/gql/components/chat.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_forward.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/widget/future_or_builder.dart
  pubspec.yaml
Labels: enhancement, k::refactor

#1234 Use `PlatformUtils.isDeltaSynchronized` flag for `AuthService.refreshSession()` guarding
  lib/domain/service/auth.dart
  lib/routes.dart
  lib/store/session.dart
  lib/ui/worker/upgrade.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
Labels: enhancement, k::refactor

#1252 Remove `FixedDigitsExtension` usage from code
  lib/domain/model/ongoing_call.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/widget/title_bar.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/chat/widget/video/widget/position.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/chats/widget/rectangular_call_button.dart
  lib/ui/page/style/page/colors/widget/color_schema.dart
  lib/ui/page/style/page/typography/widget/row.dart
  lib/util/fixed_digits.dart
Labels: enhancement, k::refactor

#1261 Send `Query.myUser` before `AuthService.refreshSession()` to ensure no connectivity errors
  lib/provider/gql/base.dart
  lib/provider/gql/components/user.dart
  lib/store/auth.dart
  test/e2e/mock/graphql.dart
Labels: enhancement, k::refactor

#1266 Omit `--wasm` flag from `build` Makefile command to disable WebAssembly renderer
  Makefile
Labels: enhancement, k::toolchain

#1267 Disable native swipe back gesture in Safari on iOS to fix invalid route animation
  CHANGELOG.md
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor, platform::web

#1272 Fix `ChatService.chats` being empty on `Participant` modal of `PopupCall`
  CHANGELOG.md
  lib/domain/repository/chat.dart
  lib/domain/service/chat.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/search/controller.dart
Labels: enhancement, k::UI/UX, k::refactor
