Repository team113/messenger, pull requests merged in 2025-07, with the labels that each got.

#1310 Bump up project version to 0.5.2
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/4.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/5.png
  android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/1.png
  android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/2.png
  android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/3.png
  android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/4.png
  android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/5.png
  android/fastlane/metadata/android/en-US/images/tenInchScreenshots/1.png
  android/fastlane/metadata/android/en-US/images/tenInchScreenshots/2.png
  android/fastlane/metadata/android/en-US/images/tenInchScreenshots/3.png
  android/fastlane/metadata/android/en-US/images/tenInchScreenshots/4.png
  android/fastlane/metadata/android/en-US/images/tenInchScreenshots/5.png
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/fastlane/metadata/en-US/release_notes.txt
  ios/fastlane/screenshots/en-US/ipadPro129_1.png
  ios/fastlane/screenshots/en-US/ipadPro129_2.png
  ios/fastlane/screenshots/en-US/ipadPro129_3.png
  ios/fastlane/screenshots/en-US/ipadPro129_4.png
  ios/fastlane/screenshots/en-US/ipadPro129_5.png
  ios/fastlane/screenshots/en-US/iphone55_1.png
  ios/fastlane/screenshots/en-US/iphone55_2.png
  ios/fastlane/screenshots/en-US/iphone55_3.png
  ios/fastlane/screenshots/en-US/iphone55_4.png
  ios/fastlane/screenshots/en-US/iphone55_5.png
  ios/fastlane/screenshots/en-US/iphone67_1.png
  ios/fastlane/screenshots/en-US/iphone67_2.png
  ios/fastlane/screenshots/en-US/iphone67_3.png
  ios/fastlane/screenshots/en-US/iphone67_4.png
  ios/fastlane/screenshots/en-US/iphone67_5.png
  lib/themes.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/home/widget/presence_label.dart
  lib/ui/widget/text_field.dart
  lib/ui/worker/cache.dart
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement, k::UI/UX, k::refactor

#1296 Redesign `AddEmail`, `DeleteEmail` and `ChangePassword` modals (#1293)
  CHANGELOG.md
  android/app/build.gradle
  assets/icons/password_grey.svg
  assets/icons/password_white2.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  helm/messenger/Chart.yaml
  lib/provider/gql/components/user.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/delete_email/controller.dart
  lib/ui/page/home/page/my_profile/delete_email/view.dart
  lib/ui/page/home/page/my_profile/password/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/widget/primary_button.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/widget/text_field.dart
  pubspec.yaml
  test/e2e/features/profile/emails/.feature
Labels: enhancement, k::UI/UX, k::refactor

#1316 Fix `Credentials` struct invalid parsing in `NotificationService` extension on iOS
  ios/NotificationServiceExtension/NotificationService.swift
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Labels: enhancement, k::refactor, platform::ios

#1287 Add Noise Suppression (#1264)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/Podfile.lock
  lib/config.dart
  lib/domain/model/media_settings.dart
  lib/domain/model/ongoing_call.dart
  lib/domain/repository/settings.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/settings.dart
  lib/store/settings.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/widget/block.dart
  lib/util/media_utils.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/e2e/features/chat/local_chat/.feature
  test/unit/noise_suppression_settings_test.dart
  windows/flutter/generated_plugin_registrant.cc
Labels: enhancement, k::UI/UX, k::refactor

#1319 Implement `Log` modal
  CHANGELOG.md
  assets/conf.toml
  lib/config.dart
  lib/domain/service/auth.dart
  lib/domain/service/notification.dart
  lib/main.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/auth/widget/animated_logo.dart
  lib/ui/page/support/log/controller.dart
  lib/ui/page/support/log/view.dart
  lib/ui/page/support/view.dart
  lib/ui/page/work/widget/interactive_logo.dart
  lib/ui/page/work/widget/project_block.dart
  lib/util/log.dart
  lib/util/platform_utils.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  test/unit/noise_suppression_settings_test.dart
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor

#1320 Fix `CallKit` VoIP notification still ringing despite already joined from another device
  CHANGELOG.md
  lib/domain/service/auth.dart
  lib/main.dart
  lib/ui/page/support/log/view.dart
  lib/ui/widget/text_field.dart
  lib/ui/worker/call.dart
  lib/ui/worker/log.dart
Labels: enhancement, k::UI/UX, k::refactor, platform::android, platform::ios

#1324 Bump up project version to 0.5.3
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  ios/fastlane/metadata/en-US/release_notes.txt
  lib/domain/model/ongoing_call.dart
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement, k::refactor

#1327 Refactor `FlutterSlider`s into separate `StyledSlider` with haptic feedback
  CHANGELOG.md
  android/app/proguard-rules.pro
  assets/icons/attachment_close.svg
  assets/icons/enter.svg
  assets/icons/one_time.svg
  assets/icons/password_small.svg
  assets/icons/password_small_white.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/l10n/l10n.dart
  lib/provider/gql/exceptions.dart
  lib/routes.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/erase/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/message_field/view.dart
  lib/ui/page/home/page/chat/message_field/widget/close_button.dart
  lib/ui/page/home/page/my_profile/add_email/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/welcome_field/view.dart
  lib/ui/page/home/page/my_profile/widget/session_tile.dart
  lib/ui/page/home/tab/menu/accounts/controller.dart
  lib/ui/page/home/tab/menu/view.dart
  lib/ui/page/login/controller.dart
  lib/ui/page/login/privacy_policy/view.dart
  lib/ui/page/login/terms_of_use/view.dart
  lib/ui/page/login/view.dart
  lib/ui/widget/menu_button.dart
  lib/ui/widget/styled_slider.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/worker/cache.dart
  lib/util/log.dart
  lib/util/media_utils.dart
  test/e2e/features/auth/create_account/.feature
  test/e2e/features/my_user/delete/.feature
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor

#1330 Redesign `StyledSlider` to have ticks
  CHANGELOG.md
  lib/domain/repository/settings.dart
  lib/provider/drift/drift.dart
  lib/store/settings.dart
  lib/ui/page/call/settings/controller.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/widget/action.dart
  lib/ui/widget/styled_slider.dart
  pubspec.lock
  pubspec.yaml
  test/unit/noise_suppression_settings_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1322 Implement a way to check whether .ftl labels are used (#1301)
  .github/workflows/ci.yml
  Makefile
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  script/fluent/.gitignore
  script/fluent/analyze.dart
  script/fluent/pubspec.yaml
Labels: enhancement, feature, k::toolchain

#1333 Add Spanish localization and update other localizations
  CHANGELOG.md
  assets/icons/remove_from_call_white.svg
  assets/icons/report_grey.svg
  assets/l10n/en-US.ftl
  assets/l10n/es-ES.ftl
  assets/l10n/ru-RU.ftl
  ios/Podfile.lock
  lib/domain/repository/chat.dart
  lib/domain/service/chat.dart
  lib/l10n/l10n.dart
  lib/store/chat.dart
  lib/ui/page/auth/account_is_not_accessible/view.dart
  lib/ui/page/auth/view.dart
  lib/ui/page/call/settings/view.dart
  lib/ui/page/erase/confirm_delete/view.dart
  lib/ui/page/home/introduction/view.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/message_info/view.dart
  lib/ui/page/home/page/chat/widget/notes_block.dart
  lib/ui/page/home/page/my_profile/add_email/view.dart
  lib/ui/page/home/page/my_profile/delete_email/view.dart
  lib/ui/page/home/page/my_profile/password/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/page/user/widget/blocklist_record.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/home/tab/contacts/view.dart
  lib/ui/page/home/tab/menu/accounts/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/widget/bottom_padded_row.dart
  lib/ui/page/home/widget/num.dart
  lib/ui/page/login/view.dart
  lib/ui/page/work/widget/project_block.dart
  lib/ui/widget/download_button.dart
  lib/ui/widget/svg/svgs.dart
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
  script/.gitignore
  script/csv_to_ftl.dart
Labels: enhancement, k::UI/UX, k::l10n, k::refactor

#1342 Fix `BottomPaddedRow` introducing meaningless paddings on `Chats` tab
  lib/domain/repository/chat.dart
  lib/domain/service/chat.dart
  lib/store/chat.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/home/page/chat/info/add_member/controller.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/widget/safe_scrollbar.dart
  lib/ui/page/support/log/view.dart
Labels: enhancement, k::UI/UX, k::refactor

#1336 Redesign routes switching on Desktop (#1311)
  CHANGELOG.md
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/widget/custom_page.dart
Labels: enhancement, k::UI/UX, k::refactor

#1345 Redesign `DeleteSession` modal
  CHANGELOG.md
  lib/domain/repository/auth.dart
  lib/domain/service/auth.dart
  lib/store/auth.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/home/page/my_profile/blocklist/view.dart
  lib/ui/page/home/page/my_profile/session/controller.dart
  lib/ui/page/home/page/my_profile/session/view.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#1349 Use `Backoff.run()` for mutations in `Chat`, `User`, `Call` and `MyUser` stores
  assets/icons/block.svg
  assets/icons/delivered.svg
  assets/icons/error.svg
  assets/icons/half_read.svg
  assets/icons/menu/interface.svg
  assets/icons/read.svg
  assets/icons/report.svg
  assets/icons/report_white.svg
  assets/icons/sending.svg
  assets/icons/sent.svg
  lib/main.dart
  lib/store/auth.dart
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/my_user.dart
  lib/store/pagination.dart
  lib/store/user.dart
  lib/ui/page/home/page/chat/widget/video/video.dart
  lib/ui/page/home/page/chat/widget/video_thumbnail/video_thumbnail.dart
  lib/ui/page/home/page/chat/widget/web_image/src/web.dart
  lib/ui/widget/download_button.dart
  lib/ui/worker/cache.dart
  lib/util/backoff.dart
  lib/util/platform_utils.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_members_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1350 Don't resubscribe `SubscriptionHandle` when `hasListener` is `false` (#1348)
  CHANGELOG.md
  lib/provider/gql/base.dart
  lib/store/auth.dart
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/my_user.dart
  lib/store/user.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/worker/upgrade.dart
  lib/util/backoff.dart
Labels: enhancement, k::UI/UX, k::refactor

#1351 Use `preventDefault()` to disable page refreshing in `PopupCall`s in browsers
  web/index.html
Labels: enhancement, k::refactor, platform::web
