Repository team113/messenger, pull requests merged in 2025-09, with the labels that each got.

#1392 Bump up Xcode version from 16.2 to 16.4 in `build` job on CI
  .github/workflows/ci.yml
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
Labels: enhancement, k::toolchain

#1405 Bump up `messenger` Helm chart version to 0.1.4
  helm/messenger/CHANGELOG.md
  helm/messenger/Chart.yaml
Labels: k::documentation, enhancement, k::deploy

#1394 [$200] Clear notifications received for specific `ChatId` when enteri…
  lib/domain/service/notification.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/util/macos_utils.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  macos/Runner/AppDelegate.swift
  macos/Runner/MainFlutterWindow.swift
  web/firebase-messaging-sw.js
Labels: enhancement, k::UI/UX, k::refactor, platform::android, platform::ios, platform::web

#1427 Remove CallButtonsPosition and its reminders from the code (#1406)
  assets/icons/make_audio_call.svg
  assets/icons/make_audio_call_disabled.svg
  assets/icons/make_audio_call_white.svg
  assets/icons/make_video_call.svg
  assets/icons/make_video_call_disabled.svg
  assets/icons/make_video_call_white.svg
  lib/domain/model/application_settings.dart
  lib/domain/repository/settings.dart
  lib/provider/drift/settings.dart
  lib/store/settings.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/widget/svg/svgs.dart
Labels: enhancement, k::refactor

#1422 Redesign `ContextMenuRegion` over `Menu` button to contain `MyUser` accounts (#1254)
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/es-ES.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/my_user.dart
  lib/ui/page/home/accounts_switcher/controller.dart
  lib/ui/page/home/accounts_switcher/view.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/tab/menu/accounts/view.dart
  lib/ui/page/home/view.dart
  lib/ui/page/home/widget/navigation_bar.dart
Labels: enhancement, k::UI/UX, k::l10n, k::refactor

#1439 Bump up project version to 0.6.4
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  ios/fastlane/metadata/en-US/release_notes.txt
  lib/ui/page/home/accounts_switcher/view.dart
  release_notes/en-US.md
  release_notes/es-ES.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement
