Repository team113/messenger, pull requests merged in 2025-01, with the labels that each got.

#1157 Fix SVGs not being displayed in `AvatarCropper` modal
  .github/workflows/ci.yml
  CHANGELOG.md
  build.yaml
  helm/messenger/Chart.yaml
  ios/Podfile.lock
  lib/config.dart
  lib/domain/model/native_file.dart
  lib/ui/page/home/page/chat/info/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/crop_avatar/controller.dart
  lib/ui/page/home/page/my_profile/crop_avatar/view.dart
  lib/ui/page/home/page/my_profile/crop_avatar/widget/image_cropper/widget.dart
  lib/ui/page/home/widget/avatar.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::UI/UX, k::refactor

#1158 Use `ChatId.local` ID instead of `ChatId` when opening `Chat`-dialogs
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/chat.dart
  lib/domain/repository/auth.dart
  lib/domain/repository/chat.dart
  lib/domain/service/auth.dart
  lib/provider/drift/chat.dart
  lib/routes.dart
  lib/store/auth.dart
  lib/store/call.dart
  lib/store/chat_rx.dart
  lib/ui/page/call/widget/conditional_backdrop.dart
  lib/ui/page/chat_direct_link/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/user/controller.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/home/tab/chats/widget/recent_chat.dart
  lib/ui/page/style/page/widgets/common/dummy_chat.dart
  lib/ui/page/work/page/backend/controller.dart
  lib/ui/page/work/page/freelance/controller.dart
  lib/ui/page/work/page/frontend/controller.dart
  lib/util/platform_utils.dart
  test/e2e/mock/platform_utils.dart
Labels: enhancement, k::UI/UX, k::refactor

#1159 Fix `ChatInfoActionMemberAdded` incrementing `Chat.membersCount` already summed up
  .github/workflows/ci.yml
  CHANGELOG.md
  android/app/proguard-rules.pro
  ios/Podfile.lock
  lib/api/backend/graphql/fragments/ChatEventsVersioned.graphql
  lib/domain/model/chat.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/my_user.dart
  lib/provider/gql/base.dart
  lib/store/call.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/my_profile/crop_avatar/widget/image_cropper/widget.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/e2e/features/user/blocklist/.feature
  web/drift_worker.js
  web/sqlite3.wasm
Labels: enhancement, k::UI/UX, k::refactor

#1160 Upgrade to 0.2.3 backend version
  .github/workflows/ci.yml
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/provider/gql/exceptions.dart
  pubspec.lock
  pubspec.yaml
  schema.graphql
Labels: enhancement, k::refactor

#1161 Use `PlatformUtils.libraryDirectory` for `drift` database directory
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/config.dart
  lib/domain/model/native_file.dart
  lib/domain/service/auth.dart
  lib/provider/drift/connection/ffi.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor

#1162 Mention child sexual abuse and exploitation (CSAE) policy in `terms.html`
  assets/terms.html
Labels: k::documentation, enhancement

#1142 Use `flutter_callkit_incoming` to support VoIP push notifications
  CHANGELOG.md
  android/app/proguard-rules.pro
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/domain/service/notification.dart
  lib/main.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/routes.dart
  lib/store/chat_rx.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/worker/call.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, feature, k::UI/UX, k::refactor, platform::ios
