Repository team113/messenger, pull requests merged in 2025-08, with the labels that each got.

#1355 Upgrade to 0.6 backend version
  .github/workflows/ci.yml
  assets/l10n/en-US.ftl
  assets/l10n/es-ES.ftl
  assets/l10n/ru-RU.ftl
  dev/backend.toml
  dev/vault/local.json
  docker-compose.yml
  lib/api/backend/graphql/fragments/ChatCallEventsVersioned.graphql
  lib/api/backend/graphql/mutation/call/ToggleCallHand.graphql
  lib/api/backend/graphql/mutation/call/TransformDialogCallIntoGroupCall.graphql
  lib/domain/repository/call.dart
  lib/domain/service/call.dart
  lib/provider/gql/components/call.dart
  lib/store/call.dart
  lib/store/event/chat_call.dart
  schema.graphql
Labels: enhancement, k::refactor, k::toolchain, k::dependencies

#1364 Use `RefreshSessionSecrets.generate()` in `AuthService.refreshSession()` (#1334)
  build.yaml
  helm/messenger/Chart.yaml
  lib/api/backend/graphql/mutation/user/RefreshSession.graphql
  lib/api/backend/graphql/parsers/session.dart
  lib/domain/model/ongoing_call.dart
  lib/domain/model/session.dart
  lib/domain/repository/auth.dart
  lib/domain/service/auth.dart
  lib/provider/gql/components/auth.dart
  lib/store/auth.dart
  pubspec.yaml
Labels: enhancement, k::refactor

#1370 Upgrade Flutter to 3.35 version
  .github/workflows/ci.yml
  Makefile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/domain/service/notification.dart
  lib/main.dart
  lib/provider/gql/base.dart
  lib/store/chat.dart
  lib/store/pagination.dart
  lib/store/pagination/combined_pagination.dart
  lib/ui/page/call/component/desktop.dart
  lib/ui/page/call/controller.dart
  lib/ui/page/call/participant/controller.dart
  lib/ui/page/call/widget/reorderable_fit.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/forward/controller.dart
  lib/ui/page/home/page/chat/info/add_member/controller.dart
  lib/ui/page/home/page/chat/info/view.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/chat/widget/chat_item.dart
  lib/ui/page/home/page/my_profile/camera_switch/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/language/view.dart
  lib/ui/page/home/page/my_profile/microphone_switch/view.dart
  lib/ui/page/home/page/my_profile/muted_chats/view.dart
  lib/ui/page/home/page/my_profile/output_switch/view.dart
  lib/ui/page/home/page/my_profile/welcome_field/controller.dart
  lib/ui/page/home/page/my_profile/widget/switch_field.dart
  lib/ui/page/home/page/user/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/widget/retry_image.dart
  lib/ui/page/player/controller.dart
  lib/ui/page/player/view.dart
  lib/ui/page/popup_call/controller.dart
  lib/ui/widget/context_menu/mobile.dart
  lib/ui/widget/custom_page.dart
  lib/ui/widget/markdown.dart
  lib/ui/widget/modal_popup.dart
  lib/ui/worker/call.dart
  lib/util/obs/sorted_map.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
  test/unit/rate_limiter_test.dart
  test_driver/integration_test_driver.dart
Labels: enhancement, k::refactor, k::dependencies

#1382 Upgrade Kotlin version to 2.1.0
  android/app/build.gradle
  android/settings.gradle
Labels: enhancement, platform::android, k::dependencies

#1386 Set `overscroll-behavior-x` to `none` in `index.html`
  CHANGELOG.md
  web/index.html
Labels: enhancement, k::UI/UX, k::refactor, platform::web
