Repository team113/messenger, pull requests merged in 2025-04, with the labels that each got.

#1193 Add `ApplicationSettings.muteKeys` binding to `MyProfile` page
  CHANGELOG.md
  assets/audio/note_muted.ogg
  assets/audio/note_unmuted.ogg
  assets/audio/pause_off.ogg
  assets/audio/pause_on.ogg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/domain/model/application_settings.dart
  lib/store/settings.dart
  lib/themes.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/widget/block.dart
  lib/ui/page/home/widget/direct_link.dart
  lib/ui/page/popup_call/controller.dart
  lib/ui/worker/call.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
Labels: enhancement, k::UI/UX, k::refactor

#1194 Redesign `ConfirmLogout` and `CallWindowSwitch` modals
  CHANGELOG.md
  assets/icons/password_white.svg
  assets/images/calls_in_app.png
  assets/images/calls_in_window.png
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  ios/NotificationServiceExtension/NotificationService.swift
  lib/l10n/l10n.dart
  lib/main.dart
  lib/ui/page/home/page/my_profile/call_window_switch/view.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/page/my_profile/widget/session_tile.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/widget/checkbox_button.dart
  lib/ui/widget/menu_button.dart
  lib/ui/widget/primary_button.dart
  lib/ui/widget/svg/svgs.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
Labels: enhancement, k::UI/UX, k::refactor

#1196 Use `MessageFieldController.onKeyUp` to enter editing of last `ChatMessage` in `Chat`
  CHANGELOG.md
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/message_field/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/tab/chats/controller.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/widget/checkbox_button.dart
  lib/ui/worker/call.dart
  lib/util/message_popup.dart
Labels: enhancement, k::UI/UX, k::refactor

#1197 Use `Locks` table to synchronize `refreshToken()` operation execution in `NotificationServiceExtension`
  CHANGELOG.md
  ios/NotificationServiceExtension/NotificationService.swift
  lib/domain/service/auth.dart
  lib/main.dart
  lib/provider/drift/call_rect.dart
  lib/provider/drift/drift.dart
  lib/provider/drift/locks.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  lib/ui/page/home/tab/menu/confirm/view.dart
  lib/ui/page/home/widget/gallery_popup.dart
  lib/ui/worker/call.dart
  test/unit/auth_test.dart
  test/unit/call_test.dart
  test/unit/chat_attachment_test.dart
  test/unit/chat_avatar_test.dart
  test/unit/chat_delete_message_test.dart
  test/unit/chat_direct_link_test.dart
  test/unit/chat_edit_message_test.dart
  test/unit/chat_hide_test.dart
  test/unit/chat_leave_test.dart
  test/unit/chat_members_test.dart
  test/unit/chat_read_test.dart
  test/unit/chat_rename_test.dart
  test/unit/chat_reply_message_test.dart
  test/unit/chat_split_message_test.dart
  test/unit/my_profile_emails_test.dart
  test/unit/my_profile_test.dart
  test/unit/my_user_muting_test.dart
  test/unit/toggle_chat_mute_test.dart
  test/widget/auth_test.dart
  test/widget/chat_attachment_test.dart
  test/widget/chat_direct_link_chat_test.dart
  test/widget/chat_edit_message_test.dart
  test/widget/chat_hide_test.dart
  test/widget/chat_rename_test.dart
  test/widget/chat_reply_message_test.dart
  test/widget/chat_update_attachments_test.dart
  test/widget/password_recovery_test.dart
  test/widget/user_profile_test.dart
Labels: enhancement, k::refactor, platform::ios

#1200 Fix `StackOverflowError` when reordering `CallButton`s in `Dock`
  lib/ui/page/call/controller.dart
  lib/ui/worker/call.dart
Labels: enhancement, k::UI/UX, k::refactor

#1195 Upgrade to 0.4.0 backend version
  assets/l10n/ru-RU.ftl
  dev/backend.toml
  docker-compose.yml
  ios/Podfile.lock
  lib/api/backend/graphql/fragments/MyUserEventsVersioned.graphql
  lib/api/backend/graphql/fragments/UserEventsVersioned.graphql
  lib/api/backend/graphql/mutation/user/RemoveUserEmail.graphql
  lib/api/backend/graphql/mutation/user/RemoveUserPhone.graphql
  lib/api/backend/graphql/query/chat/RecentChats.graphql
  lib/api/backend/graphql/subscription/chat/RecentChatsTopEvents.graphql
  lib/domain/repository/my_user.dart
  lib/domain/service/my_user.dart
  lib/provider/gql/components/chat.dart
  lib/provider/gql/components/user.dart
  lib/provider/gql/exceptions.dart
  lib/store/chat.dart
  lib/store/event/my_user.dart
  lib/store/event/user.dart
  lib/store/my_user.dart
  lib/store/user.dart
  lib/ui/page/home/introduction/controller.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/delete_email/controller.dart
  lib/ui/page/home/page/my_profile/view.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  schema.graphql
  test/e2e/mock/graphql.dart
  test/unit/my_profile_emails_test.dart
Labels: enhancement, k::refactor, k::dependencies

#1202 Bump up project version to 0.4.0
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  helm/messenger/Chart.yaml
  ios/fastlane/metadata/en-US/release_notes.txt
  pubspec.yaml
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement

#1201 Redesign `UpgradePopup` displayed on `Home` page to be downloadable
  CHANGELOG.md
  assets/icons/download_arrow.svg
  assets/icons/download_folder.svg
  assets/icons/download_refresh.svg
  assets/l10n/en-US.ftl
  assets/l10n/ru-RU.ftl
  lib/main.dart
  lib/ui/page/home/controller.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/page/my_profile/crop_avatar/controller.dart
  lib/ui/page/home/router.dart
  lib/ui/page/home/view.dart
  lib/ui/widget/download_button.dart
  lib/ui/widget/progress_indicator.dart
  lib/ui/widget/svg/svgs.dart
  lib/ui/widget/upgrade_popup/controller.dart
  lib/ui/widget/upgrade_popup/view.dart
  lib/ui/worker/upgrade.dart
  lib/util/platform_utils.dart
  macos/Podfile.lock
  test/e2e/parameters/keys.dart
  web/icons/alert/apple-icon-114x114.png
  web/icons/alert/apple-icon-120x120.png
  web/icons/alert/apple-icon-144x144.png
  web/icons/alert/apple-icon-152x152.png
  web/icons/alert/apple-icon-180x180.png
  web/icons/alert/apple-icon-57x57.png
  web/icons/alert/apple-icon-60x60.png
  web/icons/alert/apple-icon-72x72.png
  web/icons/alert/apple-icon-76x76.png
  web/icons/alert/apple-icon-precomposed.png
  web/icons/alert/apple-icon.png
Labels: enhancement, k::UI/UX, k::refactor

#1204 Bump up project version to 0.4.1
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  helm/messenger/Chart.yaml
  ios/fastlane/metadata/en-US/release_notes.txt
  pubspec.yaml
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement

#1205 Use `PlatformUtilsImpl.loadString()` to fetch assets cached according to `Pubspec.ref`
  lib/config.dart
  lib/l10n/l10n.dart
  lib/store/auth.dart
  lib/themes.dart
  lib/ui/page/home/page/chat/controller.dart
  lib/ui/page/home/page/chat/view.dart
  lib/ui/page/home/page/my_profile/controller.dart
  lib/ui/page/home/tab/chats/view.dart
  lib/ui/page/login/privacy_policy/view.dart
  lib/ui/page/login/terms_of_use/view.dart
  lib/ui/widget/svg/src/web.dart
  lib/util/audio_utils.dart
  lib/util/platform_utils.dart
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, k::refactor

#1209 Update PWA icon
  CHANGELOG.md
  ios/Podfile.lock
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  web/icons/android-icon-144x144.png
  web/icons/android-icon-192x192.png
  web/icons/android-icon-36x36.png
  web/icons/android-icon-48x48.png
  web/icons/android-icon-72x72.png
  web/icons/android-icon-96x96.png
  web/icons/apple-icon-114x114.png
  web/icons/apple-icon-120x120.png
  web/icons/apple-icon-144x144.png
  web/icons/apple-icon-152x152.png
  web/icons/apple-icon-180x180.png
  web/icons/apple-icon-57x57.png
  web/icons/apple-icon-60x60.png
  web/icons/apple-icon-72x72.png
  web/icons/apple-icon-76x76.png
  web/icons/apple-icon-precomposed.png
  web/icons/apple-icon.png
  web/icons/macOS/icon_128x128.png
  web/icons/macOS/icon_16x16.png
  web/icons/macOS/icon_256x256.png
  web/icons/macOS/icon_32x32.png
  web/icons/macOS/icon_512x512.png
  web/icons/maskable-icon.png
  web/icons/ms-icon-144x144.png
  web/icons/ms-icon-150x150.png
  web/icons/ms-icon-310x310.png
  web/icons/ms-icon-70x70.png
  web/manifest.json
Labels: enhancement, k::UI/UX, k::refactor

#1212 Guard `enumerateDevices()` and `onDeviceChange` in `OngoingCall` with `Mutex`
  lib/domain/model/ongoing_call.dart
  lib/provider/gql/base.dart
  lib/ui/worker/call.dart
  pubspec.lock
  pubspec.yaml
  test/unit/base62_to_uuid_test.dart
Labels: enhancement, k::refactor

#1213 Bump up project version to 0.4.2
  CHANGELOG.md
  android/fastlane/metadata/android/en-US/changelogs/default.txt
  ios/fastlane/metadata/en-US/release_notes.txt
  release_notes/en-US.md
  release_notes/ru-RU.md
Labels: k::documentation, enhancement

#1214 Optimize redraws in `Call`s
  lib/ui/page/call/component/desktop.dart
  macos/Podfile.lock
Labels: enhancement, k::UI/UX, k::performance, k::refactor

#1215 Add `translate="no"` to `<html>` tag in `index.html` to hide translate popup
  CHANGELOG.md
  helm/messenger/Chart.yaml
  lib/util/media_utils.dart
  pubspec.yaml
  web/index.html
Labels: enhancement, k::refactor, platform::web

#1216 Use `cupertino_http` for iOS/macOS HTTP client (#930)
  ios/Podfile.lock
  lib/provider/gql/base.dart
  lib/util/web/non_web.dart
  lib/util/web/web.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: enhancement, k::refactor, platform::macos, platform::ios

#1218 Convert `AssetAudioSorce` to `Media` using `Config.origin` prefix instead of `asset:///`
  CHANGELOG.md
  lib/util/audio_utils.dart
  web/manifest.json
Labels: enhancement, k::UI/UX, k::refactor, platform::web

#1217 Mention performance considerations in `Release.md`
  .github/PULL_REQUEST_TEMPLATE/Release.md
Labels: enhancement, k::toolchain

#1219 Fix `OngoingCall` notification displaying again after `decline()`
  CHANGELOG.md
  lib/domain/model/session.dart
  lib/domain/repository/call.dart
  lib/domain/service/auth.dart
  lib/store/call.dart
  lib/store/chat.dart
  lib/store/chat_rx.dart
  test/unit/call_test.dart
Labels: enhancement, k::UI/UX, k::refactor

#1222 Use Xcode 16 in `build` CI job
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain

#1223 Await for `Permission.microphone` to be acquired on every platform in `OngoingCall`
  CHANGELOG.md
  lib/domain/model/ongoing_call.dart
  lib/provider/drift/drift.dart
  lib/ui/page/home/overlay/controller.dart
Labels: enhancement, k::UI/UX, k::refactor

#1226 Add icons to `ContextMenuButton`s over `Participant`s in `Call`
  CHANGELOG.md
  assets/icons/call_center.svg
  assets/icons/call_center_white.svg
  assets/icons/call_cut_video.svg
  assets/icons/call_cut_video_white.svg
  assets/icons/call_de_center.svg
  assets/icons/call_de_center_white.svg
  assets/icons/call_disable_audio.svg
  assets/icons/call_disable_audio_white.svg
  assets/icons/call_disable_video.svg
  assets/icons/call_disable_video_white.svg
  assets/icons/call_enable_audio.svg
  assets/icons/call_enable_audio_white.svg
  assets/icons/call_enable_video.svg
  assets/icons/call_enable_video_white.svg
  assets/icons/call_mute.svg
  assets/icons/call_mute_white.svg
  assets/icons/call_not_cut_video.svg
  assets/icons/call_not_cut_video_white.svg
  assets/icons/call_remove_from.svg
  assets/icons/call_remove_from_white.svg
  assets/icons/call_turn_video_off.svg
  assets/icons/call_turn_video_off_white.svg
  assets/icons/call_turn_video_on.svg
  assets/icons/call_turn_video_on_white.svg
  assets/icons/call_unmute.svg
  assets/icons/call_unmute_white.svg
  lib/ui/page/call/component/desktop.dart
  lib/ui/widget/svg/svgs.dart
Labels: enhancement, k::UI/UX

#1227 Execute `getUserMedia()` in `WebUtils.microphonePermission()` for Safari
  CHANGELOG.md
  lib/util/web/web.dart
Labels: enhancement, k::UI/UX, k::refactor, platform::web
